// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface AddSessionStepFeedbackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.AddSessionStepFeedbackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the session.
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * The id of the session.
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * The id of the session step (turn) the feedback is about.
   * </pre>
   *
   * <code>string session_step_id = 2;</code>
   * @return The sessionStepId.
   */
  java.lang.String getSessionStepId();
  /**
   * <pre>
   * The id of the session step (turn) the feedback is about.
   * </pre>
   *
   * <code>string session_step_id = 2;</code>
   * @return The bytes for sessionStepId.
   */
  com.google.protobuf.ByteString
      getSessionStepIdBytes();

  /**
   * <pre>
   * The feedback to record.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFeedback feedback = 3;</code>
   * @return Whether the feedback field is set.
   */
  boolean hasFeedback();
  /**
   * <pre>
   * The feedback to record.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFeedback feedback = 3;</code>
   * @return The feedback.
   */
  com.ondewo.nlu.SessionFeedback getFeedback();
  /**
   * <pre>
   * The feedback to record.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFeedback feedback = 3;</code>
   */
  com.ondewo.nlu.SessionFeedbackOrBuilder getFeedbackOrBuilder();
}
