// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * File type of an audio resource
 * </pre>
 *
 * Protobuf enum {@code ondewo.nlu.AudioFileResourceType}
 */
@com.google.protobuf.Generated
public enum AudioFileResourceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Unspecified audio file type
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_UNSPECIFIED = 0;</code>
   */
  AUDIO_FILE_RESOURCE_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * Audio file from text to speech
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_T2S = 1;</code>
   */
  AUDIO_FILE_RESOURCE_TYPE_T2S(1),
  /**
   * <pre>
   * Audio file from speech to text
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_S2T = 2;</code>
   */
  AUDIO_FILE_RESOURCE_TYPE_S2T(2),
  /**
   * <pre>
   * Audio file from speech to text and text to speech
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_S2T_AND_T2S = 3;</code>
   */
  AUDIO_FILE_RESOURCE_TYPE_S2T_AND_T2S(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      AudioFileResourceType.class.getName());
  }
  /**
   * <pre>
   * Unspecified audio file type
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int AUDIO_FILE_RESOURCE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Audio file from text to speech
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_T2S = 1;</code>
   */
  public static final int AUDIO_FILE_RESOURCE_TYPE_T2S_VALUE = 1;
  /**
   * <pre>
   * Audio file from speech to text
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_S2T = 2;</code>
   */
  public static final int AUDIO_FILE_RESOURCE_TYPE_S2T_VALUE = 2;
  /**
   * <pre>
   * Audio file from speech to text and text to speech
   * </pre>
   *
   * <code>AUDIO_FILE_RESOURCE_TYPE_S2T_AND_T2S = 3;</code>
   */
  public static final int AUDIO_FILE_RESOURCE_TYPE_S2T_AND_T2S_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AudioFileResourceType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AudioFileResourceType forNumber(int value) {
    switch (value) {
      case 0: return AUDIO_FILE_RESOURCE_TYPE_UNSPECIFIED;
      case 1: return AUDIO_FILE_RESOURCE_TYPE_T2S;
      case 2: return AUDIO_FILE_RESOURCE_TYPE_S2T;
      case 3: return AUDIO_FILE_RESOURCE_TYPE_S2T_AND_T2S;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AudioFileResourceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AudioFileResourceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AudioFileResourceType>() {
          public AudioFileResourceType findValueByNumber(int number) {
            return AudioFileResourceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.getDescriptor().getEnumTypes().get(10);
  }

  private static final AudioFileResourceType[] VALUES = values();

  public static AudioFileResourceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AudioFileResourceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ondewo.nlu.AudioFileResourceType)
}

