// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/context.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface ContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.Context)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The display name of the context (must be unique per session).
   *
   * Note: we are deviating from the dialogflow format
   * &lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;/contexts/&amp;lt;context_uuid&amp;gt;&lt;/code&gt;.
   *
   * &lt;ul&gt;
   * &lt;li&gt;DetectIntent only returns
   * &lt;ul&gt;
   * &lt;li&gt;the short display name in the &amp;quot;name&amp;quot; field in query_result.output_contexts&lt;/li&gt;
   * &lt;li&gt;only expects the short display name in the &amp;quot;name&amp;quot; field in query_parameters.contexts&lt;/li&gt;
   * &lt;/ul&gt;
   * &lt;/li&gt;
   * &lt;li&gt;Also inside the persisted session object only the short display name is used.
   * &lt;ul&gt;
   * &lt;li&gt;SessionStep.contexts only contains the short display name&lt;/li&gt;
   * &lt;li&gt;SessionReviewStep.contexts only contains the short display name&lt;/li&gt;
   * &lt;/ul&gt;
   * &lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. The display name of the context (must be unique per session).
   *
   * Note: we are deviating from the dialogflow format
   * &lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;/contexts/&amp;lt;context_uuid&amp;gt;&lt;/code&gt;.
   *
   * &lt;ul&gt;
   * &lt;li&gt;DetectIntent only returns
   * &lt;ul&gt;
   * &lt;li&gt;the short display name in the &amp;quot;name&amp;quot; field in query_result.output_contexts&lt;/li&gt;
   * &lt;li&gt;only expects the short display name in the &amp;quot;name&amp;quot; field in query_parameters.contexts&lt;/li&gt;
   * &lt;/ul&gt;
   * &lt;/li&gt;
   * &lt;li&gt;Also inside the persisted session object only the short display name is used.
   * &lt;ul&gt;
   * &lt;li&gt;SessionStep.contexts only contains the short display name&lt;/li&gt;
   * &lt;li&gt;SessionReviewStep.contexts only contains the short display name&lt;/li&gt;
   * &lt;/ul&gt;
   * &lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Optional. The number of conversational query requests after which the
   * context expires. If set to &lt;code&gt;0&lt;/code&gt; (the default) the context expires
   * immediately. Contexts expire automatically after 10 minutes even if there
   * are no matching queries.
   * </pre>
   *
   * <code>int32 lifespan_count = 2;</code>
   * @return The lifespanCount.
   */
  int getLifespanCount();

  /**
   * <pre>
   * Optional. The collection of parameters associated with this context.
   * Refer to &lt;a href="https://dialogflow.com/docs/actions-and-parameters"&gt;this doc&lt;/a&gt; for
   * syntax.
   * Keys are the display names of context parameters.
   * </pre>
   *
   * <code>map&lt;string, .ondewo.nlu.Context.Parameter&gt; parameters = 3;</code>
   */
  int getParametersCount();
  /**
   * <pre>
   * Optional. The collection of parameters associated with this context.
   * Refer to &lt;a href="https://dialogflow.com/docs/actions-and-parameters"&gt;this doc&lt;/a&gt; for
   * syntax.
   * Keys are the display names of context parameters.
   * </pre>
   *
   * <code>map&lt;string, .ondewo.nlu.Context.Parameter&gt; parameters = 3;</code>
   */
  boolean containsParameters(
      java.lang.String key);
  /**
   * Use {@link #getParametersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.ondewo.nlu.Context.Parameter>
  getParameters();
  /**
   * <pre>
   * Optional. The collection of parameters associated with this context.
   * Refer to &lt;a href="https://dialogflow.com/docs/actions-and-parameters"&gt;this doc&lt;/a&gt; for
   * syntax.
   * Keys are the display names of context parameters.
   * </pre>
   *
   * <code>map&lt;string, .ondewo.nlu.Context.Parameter&gt; parameters = 3;</code>
   */
  java.util.Map<java.lang.String, com.ondewo.nlu.Context.Parameter>
  getParametersMap();
  /**
   * <pre>
   * Optional. The collection of parameters associated with this context.
   * Refer to &lt;a href="https://dialogflow.com/docs/actions-and-parameters"&gt;this doc&lt;/a&gt; for
   * syntax.
   * Keys are the display names of context parameters.
   * </pre>
   *
   * <code>map&lt;string, .ondewo.nlu.Context.Parameter&gt; parameters = 3;</code>
   */
  /* nullable */
com.ondewo.nlu.Context.Parameter getParametersOrDefault(
      java.lang.String key,
      /* nullable */
com.ondewo.nlu.Context.Parameter defaultValue);
  /**
   * <pre>
   * Optional. The collection of parameters associated with this context.
   * Refer to &lt;a href="https://dialogflow.com/docs/actions-and-parameters"&gt;this doc&lt;/a&gt; for
   * syntax.
   * Keys are the display names of context parameters.
   * </pre>
   *
   * <code>map&lt;string, .ondewo.nlu.Context.Parameter&gt; parameters = 3;</code>
   */
  com.ondewo.nlu.Context.Parameter getParametersOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Optional. The time span in seconds after which the context expires. By default it does not expire.
   * </pre>
   *
   * <code>optional float lifespan_time = 4;</code>
   * @return Whether the lifespanTime field is set.
   */
  boolean hasLifespanTime();
  /**
   * <pre>
   * Optional. The time span in seconds after which the context expires. By default it does not expire.
   * </pre>
   *
   * <code>optional float lifespan_time = 4;</code>
   * @return The lifespanTime.
   */
  float getLifespanTime();

  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 6;</code>
   * @return Whether the modifiedAt field is set.
   */
  boolean hasModifiedAt();
  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 6;</code>
   * @return The modifiedAt.
   */
  com.google.protobuf.Timestamp getModifiedAt();
  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedAtOrBuilder();

  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string created_by = 7;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string created_by = 7;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string modified_by = 8;</code>
   * @return The modifiedBy.
   */
  java.lang.String getModifiedBy();
  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string modified_by = 8;</code>
   * @return The bytes for modifiedBy.
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();
}
