// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/entity_type.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface DeleteEntityTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.DeleteEntityTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The name of the entity type to delete.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. The name of the entity type to delete.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
