// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface DetectedIntentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.DetectedIntent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * intent
   * </pre>
   *
   * <code>.ondewo.nlu.Intent intent = 1;</code>
   * @return Whether the intent field is set.
   */
  boolean hasIntent();
  /**
   * <pre>
   * intent
   * </pre>
   *
   * <code>.ondewo.nlu.Intent intent = 1;</code>
   * @return The intent.
   */
  ondewo.nlu.IntentOuterClass.Intent getIntent();
  /**
   * <pre>
   * intent
   * </pre>
   *
   * <code>.ondewo.nlu.Intent intent = 1;</code>
   */
  ondewo.nlu.IntentOuterClass.IntentOrBuilder getIntentOrBuilder();

  /**
   * <pre>
   * score of intent detection
   * </pre>
   *
   * <code>float score = 2;</code>
   * @return The score.
   */
  float getScore();

  /**
   * <pre>
   * intent detection algorithm
   * </pre>
   *
   * <code>string algorithm = 3;</code>
   * @return The algorithm.
   */
  java.lang.String getAlgorithm();
  /**
   * <pre>
   * intent detection algorithm
   * </pre>
   *
   * <code>string algorithm = 3;</code>
   * @return The bytes for algorithm.
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <pre>
   * collection of rich messages to present to the user
   * This field is set only for the first detected intent. For the rest of the intents the messages are not
   * resolved and the raw messages for the current language code are available in self.intent.messages
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 4;</code>
   */
  java.util.List<ondewo.nlu.IntentOuterClass.Intent.Message> 
      getFulfillmentMessagesList();
  /**
   * <pre>
   * collection of rich messages to present to the user
   * This field is set only for the first detected intent. For the rest of the intents the messages are not
   * resolved and the raw messages for the current language code are available in self.intent.messages
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 4;</code>
   */
  ondewo.nlu.IntentOuterClass.Intent.Message getFulfillmentMessages(int index);
  /**
   * <pre>
   * collection of rich messages to present to the user
   * This field is set only for the first detected intent. For the rest of the intents the messages are not
   * resolved and the raw messages for the current language code are available in self.intent.messages
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 4;</code>
   */
  int getFulfillmentMessagesCount();
  /**
   * <pre>
   * collection of rich messages to present to the user
   * This field is set only for the first detected intent. For the rest of the intents the messages are not
   * resolved and the raw messages for the current language code are available in self.intent.messages
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 4;</code>
   */
  java.util.List<? extends ondewo.nlu.IntentOuterClass.Intent.MessageOrBuilder> 
      getFulfillmentMessagesOrBuilderList();
  /**
   * <pre>
   * collection of rich messages to present to the user
   * This field is set only for the first detected intent. For the rest of the intents the messages are not
   * resolved and the raw messages for the current language code are available in self.intent.messages
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 4;</code>
   */
  ondewo.nlu.IntentOuterClass.Intent.MessageOrBuilder getFulfillmentMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * This field is set to:
   * &lt;ul&gt;
   * &lt;li&gt;&lt;code&gt;true&lt;/code&gt; if the matched intent has required parameters and not all of the required parameter values have been collected.&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;false&lt;/code&gt; if all required parameter values have been collected, or if the matched intent doesn&amp;apos;t contain any required parameters.&lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * <code>bool required_param_missing = 5;</code>
   * @return The requiredParamMissing.
   */
  boolean getRequiredParamMissing();
}
