// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/entity_type.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface EntityTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.EntityType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required for all methods except &lt;code&gt;create&lt;/code&gt; (&lt;code&gt;create&lt;/code&gt; populates the name
   * automatically.
   * The unique identifier of the entity type. Format:
   * &lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required for all methods except &lt;code&gt;create&lt;/code&gt; (&lt;code&gt;create&lt;/code&gt; populates the name
   * automatically.
   * The unique identifier of the entity type. Format:
   * &lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Required. The name of the entity type.
   * </pre>
   *
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * Required. The name of the entity type.
   * </pre>
   *
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   * Required. Indicates the kind of entity type.
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType.Kind kind = 3;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <pre>
   * Required. Indicates the kind of entity type.
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType.Kind kind = 3;</code>
   * @return The kind.
   */
  com.ondewo.nlu.EntityType.Kind getKind();

  /**
   * <pre>
   * Optional. Indicates whether the entity type can be automatically
   * expanded.
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType.AutoExpansionMode auto_expansion_mode = 4;</code>
   * @return The enum numeric value on the wire for autoExpansionMode.
   */
  int getAutoExpansionModeValue();
  /**
   * <pre>
   * Optional. Indicates whether the entity type can be automatically
   * expanded.
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType.AutoExpansionMode auto_expansion_mode = 4;</code>
   * @return The autoExpansionMode.
   */
  com.ondewo.nlu.EntityType.AutoExpansionMode getAutoExpansionMode();

  /**
   * <pre>
   * Optional. The collection of entities associated with the entity type.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType.Entity entities = 6;</code>
   */
  java.util.List<com.ondewo.nlu.EntityType.Entity> 
      getEntitiesList();
  /**
   * <pre>
   * Optional. The collection of entities associated with the entity type.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType.Entity entities = 6;</code>
   */
  com.ondewo.nlu.EntityType.Entity getEntities(int index);
  /**
   * <pre>
   * Optional. The collection of entities associated with the entity type.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType.Entity entities = 6;</code>
   */
  int getEntitiesCount();
  /**
   * <pre>
   * Optional. The collection of entities associated with the entity type.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType.Entity entities = 6;</code>
   */
  java.util.List<? extends com.ondewo.nlu.EntityType.EntityOrBuilder> 
      getEntitiesOrBuilderList();
  /**
   * <pre>
   * Optional. The collection of entities associated with the entity type.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType.Entity entities = 6;</code>
   */
  com.ondewo.nlu.EntityType.EntityOrBuilder getEntitiesOrBuilder(
      int index);

  /**
   * <pre>
   * The next_page_token is used to retrieve the next page of a returned result,
   * e.g. next_page_token is current_index-2
   * </pre>
   *
   * <code>string next_page_token = 10;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * The next_page_token is used to retrieve the next page of a returned result,
   * e.g. next_page_token is current_index-2
   * </pre>
   *
   * <code>string next_page_token = 10;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();

  /**
   * <pre>
   * Read-Only field. Total count of entity values of the entity type
   * </pre>
   *
   * <code>int32 entity_count = 11;</code>
   * @return The entityCount.
   */
  int getEntityCount();

  /**
   * <pre>
   * Indicates whether the entity type is active or not
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType.EntityTypeStatus status = 12;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Indicates whether the entity type is active or not
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType.EntityTypeStatus status = 12;</code>
   * @return The status.
   */
  com.ondewo.nlu.EntityType.EntityTypeStatus getStatus();

  /**
   * <pre>
   * Read-Only field. Total count of entity synonyms of the entity type
   * </pre>
   *
   * <code>int32 synonym_count = 13;</code>
   * @return The synonymCount.
   */
  int getSynonymCount();

  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 14;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 14;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 14;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 15;</code>
   * @return Whether the modifiedAt field is set.
   */
  boolean hasModifiedAt();
  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 15;</code>
   * @return The modifiedAt.
   */
  com.google.protobuf.Timestamp getModifiedAt();
  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 15;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedAtOrBuilder();

  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string created_by = 16;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string created_by = 16;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string modified_by = 17;</code>
   * @return The modifiedBy.
   */
  java.lang.String getModifiedBy();
  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string modified_by = 17;</code>
   * @return The bytes for modifiedBy.
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();
}
