// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * Protobuf type {@code ondewo.nlu.FeedbackBreakdownBucket}
 */
@com.google.protobuf.Generated
public final class FeedbackBreakdownBucket extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.FeedbackBreakdownBucket)
    FeedbackBreakdownBucketOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      FeedbackBreakdownBucket.class.getName());
  }
  // Use FeedbackBreakdownBucket.newBuilder() to construct.
  private FeedbackBreakdownBucket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FeedbackBreakdownBucket() {
    key_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_FeedbackBreakdownBucket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_FeedbackBreakdownBucket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.FeedbackBreakdownBucket.class, com.ondewo.nlu.FeedbackBreakdownBucket.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <pre>
   * The bucket key (e.g. a language code, an intent display name, an author type).
   * </pre>
   *
   * <code>string key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The bucket key (e.g. a language code, an intent display name, an author type).
   * </pre>
   *
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THUMBS_UP_COUNT_FIELD_NUMBER = 2;
  private int thumbsUpCount_ = 0;
  /**
   * <pre>
   * Number of thumbs-up feedback in this bucket.
   * </pre>
   *
   * <code>int32 thumbs_up_count = 2;</code>
   * @return The thumbsUpCount.
   */
  @java.lang.Override
  public int getThumbsUpCount() {
    return thumbsUpCount_;
  }

  public static final int THUMBS_DOWN_COUNT_FIELD_NUMBER = 3;
  private int thumbsDownCount_ = 0;
  /**
   * <pre>
   * Number of thumbs-down feedback in this bucket.
   * </pre>
   *
   * <code>int32 thumbs_down_count = 3;</code>
   * @return The thumbsDownCount.
   */
  @java.lang.Override
  public int getThumbsDownCount() {
    return thumbsDownCount_;
  }

  public static final int TOTAL_FIELD_NUMBER = 4;
  private int total_ = 0;
  /**
   * <pre>
   * Total feedback in this bucket (including unrated comment-only feedback).
   * </pre>
   *
   * <code>int32 total = 4;</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
    }
    if (thumbsUpCount_ != 0) {
      output.writeInt32(2, thumbsUpCount_);
    }
    if (thumbsDownCount_ != 0) {
      output.writeInt32(3, thumbsDownCount_);
    }
    if (total_ != 0) {
      output.writeInt32(4, total_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
    }
    if (thumbsUpCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, thumbsUpCount_);
    }
    if (thumbsDownCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, thumbsDownCount_);
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, total_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.FeedbackBreakdownBucket)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.FeedbackBreakdownBucket other = (com.ondewo.nlu.FeedbackBreakdownBucket) obj;

    if (!getKey()
        .equals(other.getKey())) return false;
    if (getThumbsUpCount()
        != other.getThumbsUpCount()) return false;
    if (getThumbsDownCount()
        != other.getThumbsDownCount()) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + THUMBS_UP_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getThumbsUpCount();
    hash = (37 * hash) + THUMBS_DOWN_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getThumbsDownCount();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.FeedbackBreakdownBucket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.FeedbackBreakdownBucket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.FeedbackBreakdownBucket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.FeedbackBreakdownBucket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ondewo.nlu.FeedbackBreakdownBucket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.FeedbackBreakdownBucket)
      com.ondewo.nlu.FeedbackBreakdownBucketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_FeedbackBreakdownBucket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_FeedbackBreakdownBucket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.FeedbackBreakdownBucket.class, com.ondewo.nlu.FeedbackBreakdownBucket.Builder.class);
    }

    // Construct using com.ondewo.nlu.FeedbackBreakdownBucket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      key_ = "";
      thumbsUpCount_ = 0;
      thumbsDownCount_ = 0;
      total_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_FeedbackBreakdownBucket_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.FeedbackBreakdownBucket getDefaultInstanceForType() {
      return com.ondewo.nlu.FeedbackBreakdownBucket.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.FeedbackBreakdownBucket build() {
      com.ondewo.nlu.FeedbackBreakdownBucket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.FeedbackBreakdownBucket buildPartial() {
      com.ondewo.nlu.FeedbackBreakdownBucket result = new com.ondewo.nlu.FeedbackBreakdownBucket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.FeedbackBreakdownBucket result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.key_ = key_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.thumbsUpCount_ = thumbsUpCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.thumbsDownCount_ = thumbsDownCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.total_ = total_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.FeedbackBreakdownBucket) {
        return mergeFrom((com.ondewo.nlu.FeedbackBreakdownBucket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.FeedbackBreakdownBucket other) {
      if (other == com.ondewo.nlu.FeedbackBreakdownBucket.getDefaultInstance()) return this;
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getThumbsUpCount() != 0) {
        setThumbsUpCount(other.getThumbsUpCount());
      }
      if (other.getThumbsDownCount() != 0) {
        setThumbsDownCount(other.getThumbsDownCount());
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              thumbsUpCount_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              thumbsDownCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object key_ = "";
    /**
     * <pre>
     * The bucket key (e.g. a language code, an intent display name, an author type).
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The bucket key (e.g. a language code, an intent display name, an author type).
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The bucket key (e.g. a language code, an intent display name, an author type).
     * </pre>
     *
     * <code>string key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bucket key (e.g. a language code, an intent display name, an author type).
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bucket key (e.g. a language code, an intent display name, an author type).
     * </pre>
     *
     * <code>string key = 1;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int thumbsUpCount_ ;
    /**
     * <pre>
     * Number of thumbs-up feedback in this bucket.
     * </pre>
     *
     * <code>int32 thumbs_up_count = 2;</code>
     * @return The thumbsUpCount.
     */
    @java.lang.Override
    public int getThumbsUpCount() {
      return thumbsUpCount_;
    }
    /**
     * <pre>
     * Number of thumbs-up feedback in this bucket.
     * </pre>
     *
     * <code>int32 thumbs_up_count = 2;</code>
     * @param value The thumbsUpCount to set.
     * @return This builder for chaining.
     */
    public Builder setThumbsUpCount(int value) {

      thumbsUpCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of thumbs-up feedback in this bucket.
     * </pre>
     *
     * <code>int32 thumbs_up_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearThumbsUpCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      thumbsUpCount_ = 0;
      onChanged();
      return this;
    }

    private int thumbsDownCount_ ;
    /**
     * <pre>
     * Number of thumbs-down feedback in this bucket.
     * </pre>
     *
     * <code>int32 thumbs_down_count = 3;</code>
     * @return The thumbsDownCount.
     */
    @java.lang.Override
    public int getThumbsDownCount() {
      return thumbsDownCount_;
    }
    /**
     * <pre>
     * Number of thumbs-down feedback in this bucket.
     * </pre>
     *
     * <code>int32 thumbs_down_count = 3;</code>
     * @param value The thumbsDownCount to set.
     * @return This builder for chaining.
     */
    public Builder setThumbsDownCount(int value) {

      thumbsDownCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of thumbs-down feedback in this bucket.
     * </pre>
     *
     * <code>int32 thumbs_down_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearThumbsDownCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      thumbsDownCount_ = 0;
      onChanged();
      return this;
    }

    private int total_ ;
    /**
     * <pre>
     * Total feedback in this bucket (including unrated comment-only feedback).
     * </pre>
     *
     * <code>int32 total = 4;</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <pre>
     * Total feedback in this bucket (including unrated comment-only feedback).
     * </pre>
     *
     * <code>int32 total = 4;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total feedback in this bucket (including unrated comment-only feedback).
     * </pre>
     *
     * <code>int32 total = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000008);
      total_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.FeedbackBreakdownBucket)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.FeedbackBreakdownBucket)
  private static final com.ondewo.nlu.FeedbackBreakdownBucket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.FeedbackBreakdownBucket();
  }

  public static com.ondewo.nlu.FeedbackBreakdownBucket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeedbackBreakdownBucket>
      PARSER = new com.google.protobuf.AbstractParser<FeedbackBreakdownBucket>() {
    @java.lang.Override
    public FeedbackBreakdownBucket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FeedbackBreakdownBucket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeedbackBreakdownBucket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.FeedbackBreakdownBucket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

