// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface GetFeedbackStatisticsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.GetFeedbackStatisticsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The aggregated statistics.
   * </pre>
   *
   * <code>.ondewo.nlu.FeedbackStatistics statistics = 1;</code>
   * @return Whether the statistics field is set.
   */
  boolean hasStatistics();
  /**
   * <pre>
   * The aggregated statistics.
   * </pre>
   *
   * <code>.ondewo.nlu.FeedbackStatistics statistics = 1;</code>
   * @return The statistics.
   */
  com.ondewo.nlu.FeedbackStatistics getStatistics();
  /**
   * <pre>
   * The aggregated statistics.
   * </pre>
   *
   * <code>.ondewo.nlu.FeedbackStatistics statistics = 1;</code>
   */
  com.ondewo.nlu.FeedbackStatisticsOrBuilder getStatisticsOrBuilder();
}
