// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface GetLatestSessionReviewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.GetLatestSessionReviewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier of the session for which the latest review should be returned
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * The unique identifier of the session for which the latest review should be returned
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * An enum specifying the amount of information to be returned for the desired session review
   * </pre>
   *
   * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
   * @return The enum numeric value on the wire for sessionReviewView.
   */
  int getSessionReviewViewValue();
  /**
   * <pre>
   * An enum specifying the amount of information to be returned for the desired session review
   * </pre>
   *
   * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
   * @return The sessionReviewView.
   */
  com.ondewo.nlu.SessionReview.View getSessionReviewView();

  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return Whether the fieldMask field is set.
   */
  boolean hasFieldMask();
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return The fieldMask.
   */
  com.google.protobuf.FieldMask getFieldMask();
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder();
}
