// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * This message is a request to get session review
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.GetSessionReviewRequest}
 */
@com.google.protobuf.Generated
public final class GetSessionReviewRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.GetSessionReviewRequest)
    GetSessionReviewRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      GetSessionReviewRequest.class.getName());
  }
  // Use GetSessionReviewRequest.newBuilder() to construct.
  private GetSessionReviewRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetSessionReviewRequest() {
    sessionReviewId_ = "";
    sessionReviewView_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_GetSessionReviewRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_GetSessionReviewRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.GetSessionReviewRequest.class, com.ondewo.nlu.GetSessionReviewRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_REVIEW_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionReviewId_ = "";
  /**
   * <pre>
   * The unique identifier of the session review to be returned
   * </pre>
   *
   * <code>string session_review_id = 1;</code>
   * @return The sessionReviewId.
   */
  @java.lang.Override
  public java.lang.String getSessionReviewId() {
    java.lang.Object ref = sessionReviewId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionReviewId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique identifier of the session review to be returned
   * </pre>
   *
   * <code>string session_review_id = 1;</code>
   * @return The bytes for sessionReviewId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionReviewIdBytes() {
    java.lang.Object ref = sessionReviewId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionReviewId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_REVIEW_VIEW_FIELD_NUMBER = 2;
  private int sessionReviewView_ = 0;
  /**
   * <pre>
   * The view of the session review to be returned
   * </pre>
   *
   * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
   * @return The enum numeric value on the wire for sessionReviewView.
   */
  @java.lang.Override public int getSessionReviewViewValue() {
    return sessionReviewView_;
  }
  /**
   * <pre>
   * The view of the session review to be returned
   * </pre>
   *
   * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
   * @return The sessionReviewView.
   */
  @java.lang.Override public com.ondewo.nlu.SessionReview.View getSessionReviewView() {
    com.ondewo.nlu.SessionReview.View result = com.ondewo.nlu.SessionReview.View.forNumber(sessionReviewView_);
    return result == null ? com.ondewo.nlu.SessionReview.View.UNRECOGNIZED : result;
  }

  public static final int FIELD_MASK_FIELD_NUMBER = 3;
  private com.google.protobuf.FieldMask fieldMask_;
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return Whether the fieldMask field is set.
   */
  @java.lang.Override
  public boolean hasFieldMask() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return The fieldMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getFieldMask() {
    return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
  }
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
    return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionReviewId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionReviewId_);
    }
    if (sessionReviewView_ != com.ondewo.nlu.SessionReview.View.VIEW_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, sessionReviewView_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getFieldMask());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionReviewId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionReviewId_);
    }
    if (sessionReviewView_ != com.ondewo.nlu.SessionReview.View.VIEW_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, sessionReviewView_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFieldMask());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.GetSessionReviewRequest)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.GetSessionReviewRequest other = (com.ondewo.nlu.GetSessionReviewRequest) obj;

    if (!getSessionReviewId()
        .equals(other.getSessionReviewId())) return false;
    if (sessionReviewView_ != other.sessionReviewView_) return false;
    if (hasFieldMask() != other.hasFieldMask()) return false;
    if (hasFieldMask()) {
      if (!getFieldMask()
          .equals(other.getFieldMask())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_REVIEW_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionReviewId().hashCode();
    hash = (37 * hash) + SESSION_REVIEW_VIEW_FIELD_NUMBER;
    hash = (53 * hash) + sessionReviewView_;
    if (hasFieldMask()) {
      hash = (37 * hash) + FIELD_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getFieldMask().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.GetSessionReviewRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.GetSessionReviewRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.GetSessionReviewRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.GetSessionReviewRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * This message is a request to get session review
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.GetSessionReviewRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.GetSessionReviewRequest)
      com.ondewo.nlu.GetSessionReviewRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_GetSessionReviewRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_GetSessionReviewRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.GetSessionReviewRequest.class, com.ondewo.nlu.GetSessionReviewRequest.Builder.class);
    }

    // Construct using com.ondewo.nlu.GetSessionReviewRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFieldMaskFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionReviewId_ = "";
      sessionReviewView_ = 0;
      fieldMask_ = null;
      if (fieldMaskBuilder_ != null) {
        fieldMaskBuilder_.dispose();
        fieldMaskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_GetSessionReviewRequest_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.GetSessionReviewRequest getDefaultInstanceForType() {
      return com.ondewo.nlu.GetSessionReviewRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.GetSessionReviewRequest build() {
      com.ondewo.nlu.GetSessionReviewRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.GetSessionReviewRequest buildPartial() {
      com.ondewo.nlu.GetSessionReviewRequest result = new com.ondewo.nlu.GetSessionReviewRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.GetSessionReviewRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionReviewId_ = sessionReviewId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sessionReviewView_ = sessionReviewView_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fieldMask_ = fieldMaskBuilder_ == null
            ? fieldMask_
            : fieldMaskBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.GetSessionReviewRequest) {
        return mergeFrom((com.ondewo.nlu.GetSessionReviewRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.GetSessionReviewRequest other) {
      if (other == com.ondewo.nlu.GetSessionReviewRequest.getDefaultInstance()) return this;
      if (!other.getSessionReviewId().isEmpty()) {
        sessionReviewId_ = other.sessionReviewId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.sessionReviewView_ != 0) {
        setSessionReviewViewValue(other.getSessionReviewViewValue());
      }
      if (other.hasFieldMask()) {
        mergeFieldMask(other.getFieldMask());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionReviewId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              sessionReviewView_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetFieldMaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionReviewId_ = "";
    /**
     * <pre>
     * The unique identifier of the session review to be returned
     * </pre>
     *
     * <code>string session_review_id = 1;</code>
     * @return The sessionReviewId.
     */
    public java.lang.String getSessionReviewId() {
      java.lang.Object ref = sessionReviewId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionReviewId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique identifier of the session review to be returned
     * </pre>
     *
     * <code>string session_review_id = 1;</code>
     * @return The bytes for sessionReviewId.
     */
    public com.google.protobuf.ByteString
        getSessionReviewIdBytes() {
      java.lang.Object ref = sessionReviewId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionReviewId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique identifier of the session review to be returned
     * </pre>
     *
     * <code>string session_review_id = 1;</code>
     * @param value The sessionReviewId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionReviewId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionReviewId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique identifier of the session review to be returned
     * </pre>
     *
     * <code>string session_review_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionReviewId() {
      sessionReviewId_ = getDefaultInstance().getSessionReviewId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique identifier of the session review to be returned
     * </pre>
     *
     * <code>string session_review_id = 1;</code>
     * @param value The bytes for sessionReviewId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionReviewIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionReviewId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int sessionReviewView_ = 0;
    /**
     * <pre>
     * The view of the session review to be returned
     * </pre>
     *
     * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
     * @return The enum numeric value on the wire for sessionReviewView.
     */
    @java.lang.Override public int getSessionReviewViewValue() {
      return sessionReviewView_;
    }
    /**
     * <pre>
     * The view of the session review to be returned
     * </pre>
     *
     * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
     * @param value The enum numeric value on the wire for sessionReviewView to set.
     * @return This builder for chaining.
     */
    public Builder setSessionReviewViewValue(int value) {
      sessionReviewView_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The view of the session review to be returned
     * </pre>
     *
     * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
     * @return The sessionReviewView.
     */
    @java.lang.Override
    public com.ondewo.nlu.SessionReview.View getSessionReviewView() {
      com.ondewo.nlu.SessionReview.View result = com.ondewo.nlu.SessionReview.View.forNumber(sessionReviewView_);
      return result == null ? com.ondewo.nlu.SessionReview.View.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The view of the session review to be returned
     * </pre>
     *
     * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
     * @param value The sessionReviewView to set.
     * @return This builder for chaining.
     */
    public Builder setSessionReviewView(com.ondewo.nlu.SessionReview.View value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      sessionReviewView_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The view of the session review to be returned
     * </pre>
     *
     * <code>.ondewo.nlu.SessionReview.View session_review_view = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionReviewView() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionReviewView_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.FieldMask fieldMask_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> fieldMaskBuilder_;
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     * @return Whether the fieldMask field is set.
     */
    public boolean hasFieldMask() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     * @return The fieldMask.
     */
    public com.google.protobuf.FieldMask getFieldMask() {
      if (fieldMaskBuilder_ == null) {
        return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      } else {
        return fieldMaskBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    public Builder setFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldMask_ = value;
      } else {
        fieldMaskBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    public Builder setFieldMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = builderForValue.build();
      } else {
        fieldMaskBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    public Builder mergeFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          fieldMask_ != null &&
          fieldMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
          getFieldMaskBuilder().mergeFrom(value);
        } else {
          fieldMask_ = value;
        }
      } else {
        fieldMaskBuilder_.mergeFrom(value);
      }
      if (fieldMask_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    public Builder clearFieldMask() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fieldMask_ = null;
      if (fieldMaskBuilder_ != null) {
        fieldMaskBuilder_.dispose();
        fieldMaskBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    public com.google.protobuf.FieldMask.Builder getFieldMaskBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetFieldMaskFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
      if (fieldMaskBuilder_ != null) {
        return fieldMaskBuilder_.getMessageOrBuilder();
      } else {
        return fieldMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      }
    }
    /**
     * <pre>
     * Optional. The mask to control which fields gets returned.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        internalGetFieldMaskFieldBuilder() {
      if (fieldMaskBuilder_ == null) {
        fieldMaskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getFieldMask(),
                getParentForChildren(),
                isClean());
        fieldMask_ = null;
      }
      return fieldMaskBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.GetSessionReviewRequest)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.GetSessionReviewRequest)
  private static final com.ondewo.nlu.GetSessionReviewRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.GetSessionReviewRequest();
  }

  public static com.ondewo.nlu.GetSessionReviewRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSessionReviewRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetSessionReviewRequest>() {
    @java.lang.Override
    public GetSessionReviewRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSessionReviewRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSessionReviewRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.GetSessionReviewRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

