// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface GetSessionStepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.GetSessionStepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier for the given session step
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;/sessionsteps/&amp;lt;session_step_uuid&amp;gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The unique identifier for the given session step
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;/sessionsteps/&amp;lt;session_step_uuid&amp;gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Optional. The mask to control which fields will be filled with data.
   * Example: path=["session_step.detect_intent_response.query_result.fulfillment_messages"]
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 2;</code>
   * @return Whether the fieldMask field is set.
   */
  boolean hasFieldMask();
  /**
   * <pre>
   * Optional. The mask to control which fields will be filled with data.
   * Example: path=["session_step.detect_intent_response.query_result.fulfillment_messages"]
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 2;</code>
   * @return The fieldMask.
   */
  com.google.protobuf.FieldMask getFieldMask();
  /**
   * <pre>
   * Optional. The mask to control which fields will be filled with data.
   * Example: path=["session_step.detect_intent_response.query_result.fulfillment_messages"]
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder();
}
