// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface InputAudioConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.InputAudioConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Audio encoding of the audio content to process.
   * </pre>
   *
   * <code>.ondewo.nlu.AudioEncoding audio_encoding = 1;</code>
   * @return The enum numeric value on the wire for audioEncoding.
   */
  int getAudioEncodingValue();
  /**
   * <pre>
   * Required. Audio encoding of the audio content to process.
   * </pre>
   *
   * <code>.ondewo.nlu.AudioEncoding audio_encoding = 1;</code>
   * @return The audioEncoding.
   */
  com.ondewo.nlu.AudioEncoding getAudioEncoding();

  /**
   * <pre>
   * Required. Sample rate (in Hertz) of the audio content sent in the query.
   * Refer to &lt;a href="/speech/docs/basics"&gt;Cloud Speech API documentation&lt;/a&gt; for more
   * details.
   * </pre>
   *
   * <code>int32 sample_rate_hertz = 2;</code>
   * @return The sampleRateHertz.
   */
  int getSampleRateHertz();

  /**
   * <pre>
   * Required. The language of the supplied audio. Dialogflow does not do
   * translations. See &lt;a href="https://dialogflow.com/docs/languages"&gt;Language
   * Support&lt;/a&gt; for a list of the
   * currently supported language codes. Note that queries in the same session
   * do not necessarily need to specify the same language.
   * </pre>
   *
   * <code>string language_code = 3;</code>
   * @return The languageCode.
   */
  java.lang.String getLanguageCode();
  /**
   * <pre>
   * Required. The language of the supplied audio. Dialogflow does not do
   * translations. See &lt;a href="https://dialogflow.com/docs/languages"&gt;Language
   * Support&lt;/a&gt; for a list of the
   * currently supported language codes. Note that queries in the same session
   * do not necessarily need to specify the same language.
   * </pre>
   *
   * <code>string language_code = 3;</code>
   * @return The bytes for languageCode.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <pre>
   * Optional. The collection of phrase hints which are used to boost accuracy
   * of speech recognition.
   * Refer to &lt;a href="/speech/docs/basics#phrase-hints"&gt;Cloud Speech API documentation&lt;/a&gt;
   * for more details.
   * </pre>
   *
   * <code>repeated string phrase_hints = 4;</code>
   * @return A list containing the phraseHints.
   */
  java.util.List<java.lang.String>
      getPhraseHintsList();
  /**
   * <pre>
   * Optional. The collection of phrase hints which are used to boost accuracy
   * of speech recognition.
   * Refer to &lt;a href="/speech/docs/basics#phrase-hints"&gt;Cloud Speech API documentation&lt;/a&gt;
   * for more details.
   * </pre>
   *
   * <code>repeated string phrase_hints = 4;</code>
   * @return The count of phraseHints.
   */
  int getPhraseHintsCount();
  /**
   * <pre>
   * Optional. The collection of phrase hints which are used to boost accuracy
   * of speech recognition.
   * Refer to &lt;a href="/speech/docs/basics#phrase-hints"&gt;Cloud Speech API documentation&lt;/a&gt;
   * for more details.
   * </pre>
   *
   * <code>repeated string phrase_hints = 4;</code>
   * @param index The index of the element to return.
   * @return The phraseHints at the given index.
   */
  java.lang.String getPhraseHints(int index);
  /**
   * <pre>
   * Optional. The collection of phrase hints which are used to boost accuracy
   * of speech recognition.
   * Refer to &lt;a href="/speech/docs/basics#phrase-hints"&gt;Cloud Speech API documentation&lt;/a&gt;
   * for more details.
   * </pre>
   *
   * <code>repeated string phrase_hints = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the phraseHints at the given index.
   */
  com.google.protobuf.ByteString
      getPhraseHintsBytes(int index);
}
