// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/entity_type.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * The response message for &lt;a href="index.html#ondewo.nlu.EntityTypes.ListEntityTypes"&gt;EntityTypes.ListEntityTypes&lt;/a&gt;.
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.ListEntityTypesResponse}
 */
@com.google.protobuf.Generated
public final class ListEntityTypesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.ListEntityTypesResponse)
    ListEntityTypesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ListEntityTypesResponse.class.getName());
  }
  // Use ListEntityTypesResponse.newBuilder() to construct.
  private ListEntityTypesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListEntityTypesResponse() {
    entityTypes_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_ListEntityTypesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_ListEntityTypesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.ListEntityTypesResponse.class, com.ondewo.nlu.ListEntityTypesResponse.Builder.class);
  }

  public static final int ENTITY_TYPES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.ondewo.nlu.EntityType> entityTypes_;
  /**
   * <pre>
   * The list of agent entity types. There will be a maximum number of items
   * returned based on the page_token field in the request.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ondewo.nlu.EntityType> getEntityTypesList() {
    return entityTypes_;
  }
  /**
   * <pre>
   * The list of agent entity types. There will be a maximum number of items
   * returned based on the page_token field in the request.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ondewo.nlu.EntityTypeOrBuilder> 
      getEntityTypesOrBuilderList() {
    return entityTypes_;
  }
  /**
   * <pre>
   * The list of agent entity types. There will be a maximum number of items
   * returned based on the page_token field in the request.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
   */
  @java.lang.Override
  public int getEntityTypesCount() {
    return entityTypes_.size();
  }
  /**
   * <pre>
   * The list of agent entity types. There will be a maximum number of items
   * returned based on the page_token field in the request.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.EntityType getEntityTypes(int index) {
    return entityTypes_.get(index);
  }
  /**
   * <pre>
   * The list of agent entity types. There will be a maximum number of items
   * returned based on the page_token field in the request.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.EntityTypeOrBuilder getEntityTypesOrBuilder(
      int index) {
    return entityTypes_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nextPageToken_ = "";
  /**
   * <pre>
   * The next_page_token is used to retrieve the next page of a returned result,
   * e.g. next_page_token is current_index-2
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The next_page_token is used to retrieve the next page of a returned result,
   * e.g. next_page_token is current_index-2
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entityTypes_.size(); i++) {
      output.writeMessage(1, entityTypes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nextPageToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entityTypes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entityTypes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nextPageToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.ListEntityTypesResponse)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.ListEntityTypesResponse other = (com.ondewo.nlu.ListEntityTypesResponse) obj;

    if (!getEntityTypesList()
        .equals(other.getEntityTypesList())) return false;
    if (!getNextPageToken()
        .equals(other.getNextPageToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntityTypesCount() > 0) {
      hash = (37 * hash) + ENTITY_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getEntityTypesList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.ListEntityTypesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.ListEntityTypesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.ListEntityTypesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.ListEntityTypesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message for &lt;a href="index.html#ondewo.nlu.EntityTypes.ListEntityTypes"&gt;EntityTypes.ListEntityTypes&lt;/a&gt;.
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.ListEntityTypesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.ListEntityTypesResponse)
      com.ondewo.nlu.ListEntityTypesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_ListEntityTypesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_ListEntityTypesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.ListEntityTypesResponse.class, com.ondewo.nlu.ListEntityTypesResponse.Builder.class);
    }

    // Construct using com.ondewo.nlu.ListEntityTypesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (entityTypesBuilder_ == null) {
        entityTypes_ = java.util.Collections.emptyList();
      } else {
        entityTypes_ = null;
        entityTypesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      nextPageToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_ListEntityTypesResponse_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.ListEntityTypesResponse getDefaultInstanceForType() {
      return com.ondewo.nlu.ListEntityTypesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.ListEntityTypesResponse build() {
      com.ondewo.nlu.ListEntityTypesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.ListEntityTypesResponse buildPartial() {
      com.ondewo.nlu.ListEntityTypesResponse result = new com.ondewo.nlu.ListEntityTypesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.ondewo.nlu.ListEntityTypesResponse result) {
      if (entityTypesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entityTypes_ = java.util.Collections.unmodifiableList(entityTypes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entityTypes_ = entityTypes_;
      } else {
        result.entityTypes_ = entityTypesBuilder_.build();
      }
    }

    private void buildPartial0(com.ondewo.nlu.ListEntityTypesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nextPageToken_ = nextPageToken_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.ListEntityTypesResponse) {
        return mergeFrom((com.ondewo.nlu.ListEntityTypesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.ListEntityTypesResponse other) {
      if (other == com.ondewo.nlu.ListEntityTypesResponse.getDefaultInstance()) return this;
      if (entityTypesBuilder_ == null) {
        if (!other.entityTypes_.isEmpty()) {
          if (entityTypes_.isEmpty()) {
            entityTypes_ = other.entityTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntityTypesIsMutable();
            entityTypes_.addAll(other.entityTypes_);
          }
          onChanged();
        }
      } else {
        if (!other.entityTypes_.isEmpty()) {
          if (entityTypesBuilder_.isEmpty()) {
            entityTypesBuilder_.dispose();
            entityTypesBuilder_ = null;
            entityTypes_ = other.entityTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entityTypesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetEntityTypesFieldBuilder() : null;
          } else {
            entityTypesBuilder_.addAllMessages(other.entityTypes_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ondewo.nlu.EntityType m =
                  input.readMessage(
                      com.ondewo.nlu.EntityType.parser(),
                      extensionRegistry);
              if (entityTypesBuilder_ == null) {
                ensureEntityTypesIsMutable();
                entityTypes_.add(m);
              } else {
                entityTypesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              nextPageToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ondewo.nlu.EntityType> entityTypes_ =
      java.util.Collections.emptyList();
    private void ensureEntityTypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entityTypes_ = new java.util.ArrayList<com.ondewo.nlu.EntityType>(entityTypes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.ondewo.nlu.EntityType, com.ondewo.nlu.EntityType.Builder, com.ondewo.nlu.EntityTypeOrBuilder> entityTypesBuilder_;

    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public java.util.List<com.ondewo.nlu.EntityType> getEntityTypesList() {
      if (entityTypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entityTypes_);
      } else {
        return entityTypesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public int getEntityTypesCount() {
      if (entityTypesBuilder_ == null) {
        return entityTypes_.size();
      } else {
        return entityTypesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public com.ondewo.nlu.EntityType getEntityTypes(int index) {
      if (entityTypesBuilder_ == null) {
        return entityTypes_.get(index);
      } else {
        return entityTypesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder setEntityTypes(
        int index, com.ondewo.nlu.EntityType value) {
      if (entityTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityTypesIsMutable();
        entityTypes_.set(index, value);
        onChanged();
      } else {
        entityTypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder setEntityTypes(
        int index, com.ondewo.nlu.EntityType.Builder builderForValue) {
      if (entityTypesBuilder_ == null) {
        ensureEntityTypesIsMutable();
        entityTypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        entityTypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder addEntityTypes(com.ondewo.nlu.EntityType value) {
      if (entityTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityTypesIsMutable();
        entityTypes_.add(value);
        onChanged();
      } else {
        entityTypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder addEntityTypes(
        int index, com.ondewo.nlu.EntityType value) {
      if (entityTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityTypesIsMutable();
        entityTypes_.add(index, value);
        onChanged();
      } else {
        entityTypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder addEntityTypes(
        com.ondewo.nlu.EntityType.Builder builderForValue) {
      if (entityTypesBuilder_ == null) {
        ensureEntityTypesIsMutable();
        entityTypes_.add(builderForValue.build());
        onChanged();
      } else {
        entityTypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder addEntityTypes(
        int index, com.ondewo.nlu.EntityType.Builder builderForValue) {
      if (entityTypesBuilder_ == null) {
        ensureEntityTypesIsMutable();
        entityTypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        entityTypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder addAllEntityTypes(
        java.lang.Iterable<? extends com.ondewo.nlu.EntityType> values) {
      if (entityTypesBuilder_ == null) {
        ensureEntityTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entityTypes_);
        onChanged();
      } else {
        entityTypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder clearEntityTypes() {
      if (entityTypesBuilder_ == null) {
        entityTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entityTypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public Builder removeEntityTypes(int index) {
      if (entityTypesBuilder_ == null) {
        ensureEntityTypesIsMutable();
        entityTypes_.remove(index);
        onChanged();
      } else {
        entityTypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public com.ondewo.nlu.EntityType.Builder getEntityTypesBuilder(
        int index) {
      return internalGetEntityTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public com.ondewo.nlu.EntityTypeOrBuilder getEntityTypesOrBuilder(
        int index) {
      if (entityTypesBuilder_ == null) {
        return entityTypes_.get(index);  } else {
        return entityTypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public java.util.List<? extends com.ondewo.nlu.EntityTypeOrBuilder> 
         getEntityTypesOrBuilderList() {
      if (entityTypesBuilder_ != null) {
        return entityTypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entityTypes_);
      }
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public com.ondewo.nlu.EntityType.Builder addEntityTypesBuilder() {
      return internalGetEntityTypesFieldBuilder().addBuilder(
          com.ondewo.nlu.EntityType.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public com.ondewo.nlu.EntityType.Builder addEntityTypesBuilder(
        int index) {
      return internalGetEntityTypesFieldBuilder().addBuilder(
          index, com.ondewo.nlu.EntityType.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     * </pre>
     *
     * <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    public java.util.List<com.ondewo.nlu.EntityType.Builder> 
         getEntityTypesBuilderList() {
      return internalGetEntityTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.ondewo.nlu.EntityType, com.ondewo.nlu.EntityType.Builder, com.ondewo.nlu.EntityTypeOrBuilder> 
        internalGetEntityTypesFieldBuilder() {
      if (entityTypesBuilder_ == null) {
        entityTypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.ondewo.nlu.EntityType, com.ondewo.nlu.EntityType.Builder, com.ondewo.nlu.EntityTypeOrBuilder>(
                entityTypes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entityTypes_ = null;
      }
      return entityTypesBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <pre>
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return The nextPageToken.
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return The bytes for nextPageToken.
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nextPageToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nextPageToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.ListEntityTypesResponse)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.ListEntityTypesResponse)
  private static final com.ondewo.nlu.ListEntityTypesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.ListEntityTypesResponse();
  }

  public static com.ondewo.nlu.ListEntityTypesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListEntityTypesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListEntityTypesResponse>() {
    @java.lang.Override
    public ListEntityTypesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListEntityTypesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListEntityTypesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.ListEntityTypesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

