// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface ListPlatformsOfAllSessionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.ListPlatformsOfAllSessionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The parent for which the platforms for all sessions should be listed
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * The parent for which the platforms for all sessions should be listed
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * Optional. A filter to narrow the response down to sessions of interest.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFilter session_filter = 2;</code>
   * @return Whether the sessionFilter field is set.
   */
  boolean hasSessionFilter();
  /**
   * <pre>
   * Optional. A filter to narrow the response down to sessions of interest.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFilter session_filter = 2;</code>
   * @return The sessionFilter.
   */
  com.ondewo.nlu.SessionFilter getSessionFilter();
  /**
   * <pre>
   * Optional. A filter to narrow the response down to sessions of interest.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFilter session_filter = 2;</code>
   */
  com.ondewo.nlu.SessionFilterOrBuilder getSessionFilterOrBuilder();

  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return Whether the fieldMask field is set.
   */
  boolean hasFieldMask();
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return The fieldMask.
   */
  com.google.protobuf.FieldMask getFieldMask();
  /**
   * <pre>
   * Optional. The mask to control which fields gets returned.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder();
}
