// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface LlmAgentUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.LlmAgentUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * intent_agent executor / agent name owning the calls.
   * </pre>
   *
   * <code>string agent_name = 1;</code>
   * @return The agentName.
   */
  java.lang.String getAgentName();
  /**
   * <pre>
   * intent_agent executor / agent name owning the calls.
   * </pre>
   *
   * <code>string agent_name = 1;</code>
   * @return The bytes for agentName.
   */
  com.google.protobuf.ByteString
      getAgentNameBytes();

  /**
   * <pre>
   * Optional agent role.
   * </pre>
   *
   * <code>string agent_role = 2;</code>
   * @return The agentRole.
   */
  java.lang.String getAgentRole();
  /**
   * <pre>
   * Optional agent role.
   * </pre>
   *
   * <code>string agent_role = 2;</code>
   * @return The bytes for agentRole.
   */
  com.google.protobuf.ByteString
      getAgentRoleBytes();

  /**
   * <pre>
   * Optional team name.
   * </pre>
   *
   * <code>string team_name = 3;</code>
   * @return The teamName.
   */
  java.lang.String getTeamName();
  /**
   * <pre>
   * Optional team name.
   * </pre>
   *
   * <code>string team_name = 3;</code>
   * @return The bytes for teamName.
   */
  com.google.protobuf.ByteString
      getTeamNameBytes();

  /**
   * <pre>
   * Number of LLM calls attributed to this agent in scope.
   * </pre>
   *
   * <code>int64 call_count = 4;</code>
   * @return The callCount.
   */
  long getCallCount();

  /**
   * <pre>
   * Summed token usage for this agent.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 5;</code>
   * @return Whether the llmTokenUsage field is set.
   */
  boolean hasLlmTokenUsage();
  /**
   * <pre>
   * Summed token usage for this agent.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 5;</code>
   * @return The llmTokenUsage.
   */
  com.ondewo.nlu.LlmTokenUsage getLlmTokenUsage();
  /**
   * <pre>
   * Summed token usage for this agent.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 5;</code>
   */
  com.ondewo.nlu.LlmTokenUsageOrBuilder getLlmTokenUsageOrBuilder();

  /**
   * <pre>
   * Tool-call count attributed to this agent.
   * </pre>
   *
   * <code>int64 tool_call_count = 6;</code>
   * @return The toolCallCount.
   */
  long getToolCallCount();
}
