// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface LlmCallStartedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.LlmCallStartedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Collector-assigned id grouping all events emitted for this LLM call.
   * </pre>
   *
   * <code>string llm_call_id = 1;</code>
   * @return The llmCallId.
   */
  java.lang.String getLlmCallId();
  /**
   * <pre>
   * Collector-assigned id grouping all events emitted for this LLM call.
   * </pre>
   *
   * <code>string llm_call_id = 1;</code>
   * @return The bytes for llmCallId.
   */
  com.google.protobuf.ByteString
      getLlmCallIdBytes();

  /**
   * <pre>
   * Provider tag: "autogen" | "langchain" | "openai" | "anthropic" | ...
   * </pre>
   *
   * <code>string provider = 2;</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <pre>
   * Provider tag: "autogen" | "langchain" | "openai" | "anthropic" | ...
   * </pre>
   *
   * <code>string provider = 2;</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <pre>
   * Concrete model identifier (e.g. "claude-3-5-sonnet-20241022").
   * </pre>
   *
   * <code>string model_name = 3;</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <pre>
   * Concrete model identifier (e.g. "claude-3-5-sonnet-20241022").
   * </pre>
   *
   * <code>string model_name = 3;</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <pre>
   * intent_agent executor / agent name owning the call.
   * </pre>
   *
   * <code>string agent_name = 4;</code>
   * @return The agentName.
   */
  java.lang.String getAgentName();
  /**
   * <pre>
   * intent_agent executor / agent name owning the call.
   * </pre>
   *
   * <code>string agent_name = 4;</code>
   * @return The bytes for agentName.
   */
  com.google.protobuf.ByteString
      getAgentNameBytes();

  /**
   * <pre>
   * Wall-clock start of the LLM call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 5;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <pre>
   * Wall-clock start of the LLM call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 5;</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <pre>
   * Wall-clock start of the LLM call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();
}
