// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * Emitted on a streaming DetectIntent when an LLM invocation finishes.
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.LlmCallFinishedEvent}
 */
@com.google.protobuf.Generated
public final class LlmCallFinishedEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.LlmCallFinishedEvent)
    LlmCallFinishedEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      LlmCallFinishedEvent.class.getName());
  }
  // Use LlmCallFinishedEvent.newBuilder() to construct.
  private LlmCallFinishedEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LlmCallFinishedEvent() {
    llmCallId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmCallFinishedEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmCallFinishedEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.LlmCallFinishedEvent.class, com.ondewo.nlu.LlmCallFinishedEvent.Builder.class);
  }

  private int bitField0_;
  public static final int LLM_CALL_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object llmCallId_ = "";
  /**
   * <pre>
   * Collector-assigned id grouping events for this LLM call.
   * </pre>
   *
   * <code>string llm_call_id = 1;</code>
   * @return The llmCallId.
   */
  @java.lang.Override
  public java.lang.String getLlmCallId() {
    java.lang.Object ref = llmCallId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      llmCallId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Collector-assigned id grouping events for this LLM call.
   * </pre>
   *
   * <code>string llm_call_id = 1;</code>
   * @return The bytes for llmCallId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLlmCallIdBytes() {
    java.lang.Object ref = llmCallId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      llmCallId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int END_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp endTime_;
  /**
   * <pre>
   * Wall-clock end time of the LLM call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 2;</code>
   * @return Whether the endTime field is set.
   */
  @java.lang.Override
  public boolean hasEndTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Wall-clock end time of the LLM call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 2;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEndTime() {
    return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
  }
  /**
   * <pre>
   * Wall-clock end time of the LLM call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder() {
    return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
  }

  public static final int DURATION_IN_S_FIELD_NUMBER = 3;
  private double durationInS_ = 0D;
  /**
   * <pre>
   * Convenience duration (end_time - start_time).
   * </pre>
   *
   * <code>double duration_in_s = 3;</code>
   * @return The durationInS.
   */
  @java.lang.Override
  public double getDurationInS() {
    return durationInS_;
  }

  public static final int LLM_TOKEN_USAGE_FIELD_NUMBER = 4;
  private com.ondewo.nlu.LlmTokenUsage llmTokenUsage_;
  /**
   * <pre>
   * Final token totals for this LLM call.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
   * @return Whether the llmTokenUsage field is set.
   */
  @java.lang.Override
  public boolean hasLlmTokenUsage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Final token totals for this LLM call.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
   * @return The llmTokenUsage.
   */
  @java.lang.Override
  public com.ondewo.nlu.LlmTokenUsage getLlmTokenUsage() {
    return llmTokenUsage_ == null ? com.ondewo.nlu.LlmTokenUsage.getDefaultInstance() : llmTokenUsage_;
  }
  /**
   * <pre>
   * Final token totals for this LLM call.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.LlmTokenUsageOrBuilder getLlmTokenUsageOrBuilder() {
    return llmTokenUsage_ == null ? com.ondewo.nlu.LlmTokenUsage.getDefaultInstance() : llmTokenUsage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(llmCallId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, llmCallId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getEndTime());
    }
    if (java.lang.Double.doubleToRawLongBits(durationInS_) != 0) {
      output.writeDouble(3, durationInS_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getLlmTokenUsage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(llmCallId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, llmCallId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndTime());
    }
    if (java.lang.Double.doubleToRawLongBits(durationInS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, durationInS_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLlmTokenUsage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.LlmCallFinishedEvent)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.LlmCallFinishedEvent other = (com.ondewo.nlu.LlmCallFinishedEvent) obj;

    if (!getLlmCallId()
        .equals(other.getLlmCallId())) return false;
    if (hasEndTime() != other.hasEndTime()) return false;
    if (hasEndTime()) {
      if (!getEndTime()
          .equals(other.getEndTime())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getDurationInS())
        != java.lang.Double.doubleToLongBits(
            other.getDurationInS())) return false;
    if (hasLlmTokenUsage() != other.hasLlmTokenUsage()) return false;
    if (hasLlmTokenUsage()) {
      if (!getLlmTokenUsage()
          .equals(other.getLlmTokenUsage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LLM_CALL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLlmCallId().hashCode();
    if (hasEndTime()) {
      hash = (37 * hash) + END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
    }
    hash = (37 * hash) + DURATION_IN_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDurationInS()));
    if (hasLlmTokenUsage()) {
      hash = (37 * hash) + LLM_TOKEN_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLlmTokenUsage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.LlmCallFinishedEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.LlmCallFinishedEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.LlmCallFinishedEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.LlmCallFinishedEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Emitted on a streaming DetectIntent when an LLM invocation finishes.
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.LlmCallFinishedEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.LlmCallFinishedEvent)
      com.ondewo.nlu.LlmCallFinishedEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmCallFinishedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmCallFinishedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.LlmCallFinishedEvent.class, com.ondewo.nlu.LlmCallFinishedEvent.Builder.class);
    }

    // Construct using com.ondewo.nlu.LlmCallFinishedEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetEndTimeFieldBuilder();
        internalGetLlmTokenUsageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      llmCallId_ = "";
      endTime_ = null;
      if (endTimeBuilder_ != null) {
        endTimeBuilder_.dispose();
        endTimeBuilder_ = null;
      }
      durationInS_ = 0D;
      llmTokenUsage_ = null;
      if (llmTokenUsageBuilder_ != null) {
        llmTokenUsageBuilder_.dispose();
        llmTokenUsageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmCallFinishedEvent_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.LlmCallFinishedEvent getDefaultInstanceForType() {
      return com.ondewo.nlu.LlmCallFinishedEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.LlmCallFinishedEvent build() {
      com.ondewo.nlu.LlmCallFinishedEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.LlmCallFinishedEvent buildPartial() {
      com.ondewo.nlu.LlmCallFinishedEvent result = new com.ondewo.nlu.LlmCallFinishedEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.LlmCallFinishedEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.llmCallId_ = llmCallId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endTime_ = endTimeBuilder_ == null
            ? endTime_
            : endTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.durationInS_ = durationInS_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.llmTokenUsage_ = llmTokenUsageBuilder_ == null
            ? llmTokenUsage_
            : llmTokenUsageBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.LlmCallFinishedEvent) {
        return mergeFrom((com.ondewo.nlu.LlmCallFinishedEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.LlmCallFinishedEvent other) {
      if (other == com.ondewo.nlu.LlmCallFinishedEvent.getDefaultInstance()) return this;
      if (!other.getLlmCallId().isEmpty()) {
        llmCallId_ = other.llmCallId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasEndTime()) {
        mergeEndTime(other.getEndTime());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getDurationInS()) != 0) {
        setDurationInS(other.getDurationInS());
      }
      if (other.hasLlmTokenUsage()) {
        mergeLlmTokenUsage(other.getLlmTokenUsage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              llmCallId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetEndTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              durationInS_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              input.readMessage(
                  internalGetLlmTokenUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object llmCallId_ = "";
    /**
     * <pre>
     * Collector-assigned id grouping events for this LLM call.
     * </pre>
     *
     * <code>string llm_call_id = 1;</code>
     * @return The llmCallId.
     */
    public java.lang.String getLlmCallId() {
      java.lang.Object ref = llmCallId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        llmCallId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Collector-assigned id grouping events for this LLM call.
     * </pre>
     *
     * <code>string llm_call_id = 1;</code>
     * @return The bytes for llmCallId.
     */
    public com.google.protobuf.ByteString
        getLlmCallIdBytes() {
      java.lang.Object ref = llmCallId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        llmCallId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Collector-assigned id grouping events for this LLM call.
     * </pre>
     *
     * <code>string llm_call_id = 1;</code>
     * @param value The llmCallId to set.
     * @return This builder for chaining.
     */
    public Builder setLlmCallId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      llmCallId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Collector-assigned id grouping events for this LLM call.
     * </pre>
     *
     * <code>string llm_call_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLlmCallId() {
      llmCallId_ = getDefaultInstance().getLlmCallId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Collector-assigned id grouping events for this LLM call.
     * </pre>
     *
     * <code>string llm_call_id = 1;</code>
     * @param value The bytes for llmCallId to set.
     * @return This builder for chaining.
     */
    public Builder setLlmCallIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      llmCallId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp endTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endTimeBuilder_;
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     * @return Whether the endTime field is set.
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     * @return The endTime.
     */
    public com.google.protobuf.Timestamp getEndTime() {
      if (endTimeBuilder_ == null) {
        return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
      } else {
        return endTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    public Builder setEndTime(com.google.protobuf.Timestamp value) {
      if (endTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endTime_ = value;
      } else {
        endTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    public Builder setEndTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endTimeBuilder_ == null) {
        endTime_ = builderForValue.build();
      } else {
        endTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    public Builder mergeEndTime(com.google.protobuf.Timestamp value) {
      if (endTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          endTime_ != null &&
          endTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getEndTimeBuilder().mergeFrom(value);
        } else {
          endTime_ = value;
        }
      } else {
        endTimeBuilder_.mergeFrom(value);
      }
      if (endTime_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endTime_ = null;
      if (endTimeBuilder_ != null) {
        endTimeBuilder_.dispose();
        endTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndTimeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetEndTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder() {
      if (endTimeBuilder_ != null) {
        return endTimeBuilder_.getMessageOrBuilder();
      } else {
        return endTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
      }
    }
    /**
     * <pre>
     * Wall-clock end time of the LLM call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetEndTimeFieldBuilder() {
      if (endTimeBuilder_ == null) {
        endTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEndTime(),
                getParentForChildren(),
                isClean());
        endTime_ = null;
      }
      return endTimeBuilder_;
    }

    private double durationInS_ ;
    /**
     * <pre>
     * Convenience duration (end_time - start_time).
     * </pre>
     *
     * <code>double duration_in_s = 3;</code>
     * @return The durationInS.
     */
    @java.lang.Override
    public double getDurationInS() {
      return durationInS_;
    }
    /**
     * <pre>
     * Convenience duration (end_time - start_time).
     * </pre>
     *
     * <code>double duration_in_s = 3;</code>
     * @param value The durationInS to set.
     * @return This builder for chaining.
     */
    public Builder setDurationInS(double value) {

      durationInS_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Convenience duration (end_time - start_time).
     * </pre>
     *
     * <code>double duration_in_s = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationInS() {
      bitField0_ = (bitField0_ & ~0x00000004);
      durationInS_ = 0D;
      onChanged();
      return this;
    }

    private com.ondewo.nlu.LlmTokenUsage llmTokenUsage_;
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.LlmTokenUsage, com.ondewo.nlu.LlmTokenUsage.Builder, com.ondewo.nlu.LlmTokenUsageOrBuilder> llmTokenUsageBuilder_;
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     * @return Whether the llmTokenUsage field is set.
     */
    public boolean hasLlmTokenUsage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     * @return The llmTokenUsage.
     */
    public com.ondewo.nlu.LlmTokenUsage getLlmTokenUsage() {
      if (llmTokenUsageBuilder_ == null) {
        return llmTokenUsage_ == null ? com.ondewo.nlu.LlmTokenUsage.getDefaultInstance() : llmTokenUsage_;
      } else {
        return llmTokenUsageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    public Builder setLlmTokenUsage(com.ondewo.nlu.LlmTokenUsage value) {
      if (llmTokenUsageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        llmTokenUsage_ = value;
      } else {
        llmTokenUsageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    public Builder setLlmTokenUsage(
        com.ondewo.nlu.LlmTokenUsage.Builder builderForValue) {
      if (llmTokenUsageBuilder_ == null) {
        llmTokenUsage_ = builderForValue.build();
      } else {
        llmTokenUsageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    public Builder mergeLlmTokenUsage(com.ondewo.nlu.LlmTokenUsage value) {
      if (llmTokenUsageBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          llmTokenUsage_ != null &&
          llmTokenUsage_ != com.ondewo.nlu.LlmTokenUsage.getDefaultInstance()) {
          getLlmTokenUsageBuilder().mergeFrom(value);
        } else {
          llmTokenUsage_ = value;
        }
      } else {
        llmTokenUsageBuilder_.mergeFrom(value);
      }
      if (llmTokenUsage_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    public Builder clearLlmTokenUsage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      llmTokenUsage_ = null;
      if (llmTokenUsageBuilder_ != null) {
        llmTokenUsageBuilder_.dispose();
        llmTokenUsageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    public com.ondewo.nlu.LlmTokenUsage.Builder getLlmTokenUsageBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetLlmTokenUsageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    public com.ondewo.nlu.LlmTokenUsageOrBuilder getLlmTokenUsageOrBuilder() {
      if (llmTokenUsageBuilder_ != null) {
        return llmTokenUsageBuilder_.getMessageOrBuilder();
      } else {
        return llmTokenUsage_ == null ?
            com.ondewo.nlu.LlmTokenUsage.getDefaultInstance() : llmTokenUsage_;
      }
    }
    /**
     * <pre>
     * Final token totals for this LLM call.
     * </pre>
     *
     * <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.LlmTokenUsage, com.ondewo.nlu.LlmTokenUsage.Builder, com.ondewo.nlu.LlmTokenUsageOrBuilder> 
        internalGetLlmTokenUsageFieldBuilder() {
      if (llmTokenUsageBuilder_ == null) {
        llmTokenUsageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.ondewo.nlu.LlmTokenUsage, com.ondewo.nlu.LlmTokenUsage.Builder, com.ondewo.nlu.LlmTokenUsageOrBuilder>(
                getLlmTokenUsage(),
                getParentForChildren(),
                isClean());
        llmTokenUsage_ = null;
      }
      return llmTokenUsageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.LlmCallFinishedEvent)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.LlmCallFinishedEvent)
  private static final com.ondewo.nlu.LlmCallFinishedEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.LlmCallFinishedEvent();
  }

  public static com.ondewo.nlu.LlmCallFinishedEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LlmCallFinishedEvent>
      PARSER = new com.google.protobuf.AbstractParser<LlmCallFinishedEvent>() {
    @java.lang.Override
    public LlmCallFinishedEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LlmCallFinishedEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LlmCallFinishedEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.LlmCallFinishedEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

