// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * Per-category native-safety aggregate across the LLM calls in scope.
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.LlmSafetyCategoryStat}
 */
@com.google.protobuf.Generated
public final class LlmSafetyCategoryStat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.LlmSafetyCategoryStat)
    LlmSafetyCategoryStatOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      LlmSafetyCategoryStat.class.getName());
  }
  // Use LlmSafetyCategoryStat.newBuilder() to construct.
  private LlmSafetyCategoryStat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LlmSafetyCategoryStat() {
    category_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmSafetyCategoryStat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmSafetyCategoryStat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.LlmSafetyCategoryStat.class, com.ondewo.nlu.LlmSafetyCategoryStat.Builder.class);
  }

  public static final int CATEGORY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <pre>
   * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
   * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
   * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private long count_ = 0L;
  /**
   * <pre>
   * Number of calls flagged for this category in scope.
   * </pre>
   *
   * <code>int64 count = 2;</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }

  public static final int RATE_FIELD_NUMBER = 3;
  private double rate_ = 0D;
  /**
   * <pre>
   * count / total_assessed.
   * </pre>
   *
   * <code>double rate = 3;</code>
   * @return The rate.
   */
  @java.lang.Override
  public double getRate() {
    return rate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, category_);
    }
    if (count_ != 0L) {
      output.writeInt64(2, count_);
    }
    if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
      output.writeDouble(3, rate_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, category_);
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, count_);
    }
    if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, rate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.LlmSafetyCategoryStat)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.LlmSafetyCategoryStat other = (com.ondewo.nlu.LlmSafetyCategoryStat) obj;

    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (getCount()
        != other.getCount()) return false;
    if (java.lang.Double.doubleToLongBits(getRate())
        != java.lang.Double.doubleToLongBits(
            other.getRate())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCount());
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRate()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.LlmSafetyCategoryStat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.LlmSafetyCategoryStat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.LlmSafetyCategoryStat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.LlmSafetyCategoryStat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Per-category native-safety aggregate across the LLM calls in scope.
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.LlmSafetyCategoryStat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.LlmSafetyCategoryStat)
      com.ondewo.nlu.LlmSafetyCategoryStatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmSafetyCategoryStat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmSafetyCategoryStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.LlmSafetyCategoryStat.class, com.ondewo.nlu.LlmSafetyCategoryStat.Builder.class);
    }

    // Construct using com.ondewo.nlu.LlmSafetyCategoryStat.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      category_ = "";
      count_ = 0L;
      rate_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_LlmSafetyCategoryStat_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.LlmSafetyCategoryStat getDefaultInstanceForType() {
      return com.ondewo.nlu.LlmSafetyCategoryStat.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.LlmSafetyCategoryStat build() {
      com.ondewo.nlu.LlmSafetyCategoryStat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.LlmSafetyCategoryStat buildPartial() {
      com.ondewo.nlu.LlmSafetyCategoryStat result = new com.ondewo.nlu.LlmSafetyCategoryStat(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.LlmSafetyCategoryStat result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.category_ = category_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.count_ = count_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rate_ = rate_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.LlmSafetyCategoryStat) {
        return mergeFrom((com.ondewo.nlu.LlmSafetyCategoryStat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.LlmSafetyCategoryStat other) {
      if (other == com.ondewo.nlu.LlmSafetyCategoryStat.getDefaultInstance()) return this;
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getRate()) != 0) {
        setRate(other.getRate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              count_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 25: {
              rate_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object category_ = "";
    /**
     * <pre>
     * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
     * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
     * </pre>
     *
     * <code>string category = 1;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
     * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
     * </pre>
     *
     * <code>string category = 1;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
     * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
     * </pre>
     *
     * <code>string category = 1;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
     * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
     * </pre>
     *
     * <code>string category = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
     * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
     * </pre>
     *
     * <code>string category = 1;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long count_ ;
    /**
     * <pre>
     * Number of calls flagged for this category in scope.
     * </pre>
     *
     * <code>int64 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }
    /**
     * <pre>
     * Number of calls flagged for this category in scope.
     * </pre>
     *
     * <code>int64 count = 2;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {

      count_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of calls flagged for this category in scope.
     * </pre>
     *
     * <code>int64 count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      count_ = 0L;
      onChanged();
      return this;
    }

    private double rate_ ;
    /**
     * <pre>
     * count / total_assessed.
     * </pre>
     *
     * <code>double rate = 3;</code>
     * @return The rate.
     */
    @java.lang.Override
    public double getRate() {
      return rate_;
    }
    /**
     * <pre>
     * count / total_assessed.
     * </pre>
     *
     * <code>double rate = 3;</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(double value) {

      rate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * count / total_assessed.
     * </pre>
     *
     * <code>double rate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rate_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.LlmSafetyCategoryStat)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.LlmSafetyCategoryStat)
  private static final com.ondewo.nlu.LlmSafetyCategoryStat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.LlmSafetyCategoryStat();
  }

  public static com.ondewo.nlu.LlmSafetyCategoryStat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LlmSafetyCategoryStat>
      PARSER = new com.google.protobuf.AbstractParser<LlmSafetyCategoryStat>() {
    @java.lang.Override
    public LlmSafetyCategoryStat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LlmSafetyCategoryStat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LlmSafetyCategoryStat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.LlmSafetyCategoryStat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

