// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface LlmSafetyCategoryStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.LlmSafetyCategoryStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
   * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * Detector category (&lt;code&gt;prompt_injection&lt;/code&gt; | &lt;code&gt;jailbreak&lt;/code&gt; |
   * &lt;code&gt;pii&lt;/code&gt; | &lt;code&gt;info_leak&lt;/code&gt;).
   * </pre>
   *
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <pre>
   * Number of calls flagged for this category in scope.
   * </pre>
   *
   * <code>int64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <pre>
   * count / total_assessed.
   * </pre>
   *
   * <code>double rate = 3;</code>
   * @return The rate.
   */
  double getRate();
}
