// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface QueryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.QueryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The original conversational query text:
   * &lt;ul&gt;
   * &lt;li&gt;If natural language text was provided as input, &lt;code&gt;query_text&lt;/code&gt; contains
   * a copy of the input.&lt;/li&gt;
   * &lt;li&gt;If natural language speech audio was provided as input, &lt;code&gt;query_text&lt;/code&gt;
   * contains the speech recognition result. If speech recognizer produced
   * multiple alternatives, a particular one is picked.&lt;/li&gt;
   * &lt;li&gt;If an event was provided as input, &lt;code&gt;query_text&lt;/code&gt; is not set.&lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * <code>string query_text = 1;</code>
   * @return The queryText.
   */
  java.lang.String getQueryText();
  /**
   * <pre>
   * The original conversational query text:
   * &lt;ul&gt;
   * &lt;li&gt;If natural language text was provided as input, &lt;code&gt;query_text&lt;/code&gt; contains
   * a copy of the input.&lt;/li&gt;
   * &lt;li&gt;If natural language speech audio was provided as input, &lt;code&gt;query_text&lt;/code&gt;
   * contains the speech recognition result. If speech recognizer produced
   * multiple alternatives, a particular one is picked.&lt;/li&gt;
   * &lt;li&gt;If an event was provided as input, &lt;code&gt;query_text&lt;/code&gt; is not set.&lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * <code>string query_text = 1;</code>
   * @return The bytes for queryText.
   */
  com.google.protobuf.ByteString
      getQueryTextBytes();

  /**
   * <pre>
   * The Speech recognition confidence between 0.0 and 1.0. A higher number
   * indicates an estimated greater likelihood that the recognized words are
   * correct. The default of 0.0 is a sentinel value indicating that confidence
   * was not set.
   *
   * You should not rely on this field as it isn&amp;apos;t guaranteed to be accurate, or
   * even set. In particular this field isn&amp;apos;t set in Webhook calls and for
   * StreamingDetectIntent since the streaming endpoint has separate confidence
   * estimates per portion of the audio in StreamingRecognitionResult.
   * </pre>
   *
   * <code>float speech_recognition_confidence = 2;</code>
   * @return The speechRecognitionConfidence.
   */
  float getSpeechRecognitionConfidence();

  /**
   * <pre>
   * The action name from the matched intent.
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * The action name from the matched intent.
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * The collection of extracted parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct parameters = 4;</code>
   * @return Whether the parameters field is set.
   */
  boolean hasParameters();
  /**
   * <pre>
   * The collection of extracted parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct parameters = 4;</code>
   * @return The parameters.
   */
  com.google.protobuf.Struct getParameters();
  /**
   * <pre>
   * The collection of extracted parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct parameters = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getParametersOrBuilder();

  /**
   * <pre>
   * This field is set to:
   * &lt;ul&gt;
   * &lt;li&gt;&lt;code&gt;false&lt;/code&gt; if the matched intent has required parameters and not all of
   * the required parameter values have been collected.&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;true&lt;/code&gt; if all required parameter values have been collected, or if the
   * matched intent doesn&amp;apos;t contain any required parameters.&lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * <code>bool all_required_params_present = 5;</code>
   * @return The allRequiredParamsPresent.
   */
  boolean getAllRequiredParamsPresent();

  /**
   * <pre>
   * The text to be pronounced to the user or shown on the screen.
   * </pre>
   *
   * <code>string fulfillment_text = 6;</code>
   * @return The fulfillmentText.
   */
  java.lang.String getFulfillmentText();
  /**
   * <pre>
   * The text to be pronounced to the user or shown on the screen.
   * </pre>
   *
   * <code>string fulfillment_text = 6;</code>
   * @return The bytes for fulfillmentText.
   */
  com.google.protobuf.ByteString
      getFulfillmentTextBytes();

  /**
   * <pre>
   * The collection of rich messages to present to the user.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 7;</code>
   */
  java.util.List<ondewo.nlu.IntentOuterClass.Intent.Message> 
      getFulfillmentMessagesList();
  /**
   * <pre>
   * The collection of rich messages to present to the user.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 7;</code>
   */
  ondewo.nlu.IntentOuterClass.Intent.Message getFulfillmentMessages(int index);
  /**
   * <pre>
   * The collection of rich messages to present to the user.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 7;</code>
   */
  int getFulfillmentMessagesCount();
  /**
   * <pre>
   * The collection of rich messages to present to the user.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 7;</code>
   */
  java.util.List<? extends ondewo.nlu.IntentOuterClass.Intent.MessageOrBuilder> 
      getFulfillmentMessagesOrBuilderList();
  /**
   * <pre>
   * The collection of rich messages to present to the user.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Intent.Message fulfillment_messages = 7;</code>
   */
  ondewo.nlu.IntentOuterClass.Intent.MessageOrBuilder getFulfillmentMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * If the query was fulfilled by a webhook call, this field is set to the
   * value of the &lt;code&gt;source&lt;/code&gt; field returned in the webhook response.
   * </pre>
   *
   * <code>string webhook_source = 8;</code>
   * @return The webhookSource.
   */
  java.lang.String getWebhookSource();
  /**
   * <pre>
   * If the query was fulfilled by a webhook call, this field is set to the
   * value of the &lt;code&gt;source&lt;/code&gt; field returned in the webhook response.
   * </pre>
   *
   * <code>string webhook_source = 8;</code>
   * @return The bytes for webhookSource.
   */
  com.google.protobuf.ByteString
      getWebhookSourceBytes();

  /**
   * <pre>
   * If the query was fulfilled by a webhook call, this field is set to the
   * value of the &lt;code&gt;payload&lt;/code&gt; field returned in the webhook response.
   * </pre>
   *
   * <code>.google.protobuf.Struct webhook_payload = 9;</code>
   * @return Whether the webhookPayload field is set.
   */
  boolean hasWebhookPayload();
  /**
   * <pre>
   * If the query was fulfilled by a webhook call, this field is set to the
   * value of the &lt;code&gt;payload&lt;/code&gt; field returned in the webhook response.
   * </pre>
   *
   * <code>.google.protobuf.Struct webhook_payload = 9;</code>
   * @return The webhookPayload.
   */
  com.google.protobuf.Struct getWebhookPayload();
  /**
   * <pre>
   * If the query was fulfilled by a webhook call, this field is set to the
   * value of the &lt;code&gt;payload&lt;/code&gt; field returned in the webhook response.
   * </pre>
   *
   * <code>.google.protobuf.Struct webhook_payload = 9;</code>
   */
  com.google.protobuf.StructOrBuilder getWebhookPayloadOrBuilder();

  /**
   * <pre>
   * The collection of output contexts. If applicable,
   * &lt;code&gt;output_contexts.parameters&lt;/code&gt; contains entries with name
   * &lt;code&gt;&amp;lt;parameter name&amp;gt;.original&lt;/code&gt; containing the original parameter values
   * before the query.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context output_contexts = 10;</code>
   */
  java.util.List<com.ondewo.nlu.Context> 
      getOutputContextsList();
  /**
   * <pre>
   * The collection of output contexts. If applicable,
   * &lt;code&gt;output_contexts.parameters&lt;/code&gt; contains entries with name
   * &lt;code&gt;&amp;lt;parameter name&amp;gt;.original&lt;/code&gt; containing the original parameter values
   * before the query.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context output_contexts = 10;</code>
   */
  com.ondewo.nlu.Context getOutputContexts(int index);
  /**
   * <pre>
   * The collection of output contexts. If applicable,
   * &lt;code&gt;output_contexts.parameters&lt;/code&gt; contains entries with name
   * &lt;code&gt;&amp;lt;parameter name&amp;gt;.original&lt;/code&gt; containing the original parameter values
   * before the query.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context output_contexts = 10;</code>
   */
  int getOutputContextsCount();
  /**
   * <pre>
   * The collection of output contexts. If applicable,
   * &lt;code&gt;output_contexts.parameters&lt;/code&gt; contains entries with name
   * &lt;code&gt;&amp;lt;parameter name&amp;gt;.original&lt;/code&gt; containing the original parameter values
   * before the query.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context output_contexts = 10;</code>
   */
  java.util.List<? extends com.ondewo.nlu.ContextOrBuilder> 
      getOutputContextsOrBuilderList();
  /**
   * <pre>
   * The collection of output contexts. If applicable,
   * &lt;code&gt;output_contexts.parameters&lt;/code&gt; contains entries with name
   * &lt;code&gt;&amp;lt;parameter name&amp;gt;.original&lt;/code&gt; containing the original parameter values
   * before the query.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context output_contexts = 10;</code>
   */
  com.ondewo.nlu.ContextOrBuilder getOutputContextsOrBuilder(
      int index);

  /**
   * <pre>
   * The intent that matched the conversational query. Some, not
   * all fields are filled in this message, including but not limited to:
   * &lt;code&gt;name&lt;/code&gt;, &lt;code&gt;display_name&lt;/code&gt; and &lt;code&gt;webhook_state&lt;/code&gt;.
   * </pre>
   *
   * <code>.ondewo.nlu.Intent intent = 11;</code>
   * @return Whether the intent field is set.
   */
  boolean hasIntent();
  /**
   * <pre>
   * The intent that matched the conversational query. Some, not
   * all fields are filled in this message, including but not limited to:
   * &lt;code&gt;name&lt;/code&gt;, &lt;code&gt;display_name&lt;/code&gt; and &lt;code&gt;webhook_state&lt;/code&gt;.
   * </pre>
   *
   * <code>.ondewo.nlu.Intent intent = 11;</code>
   * @return The intent.
   */
  ondewo.nlu.IntentOuterClass.Intent getIntent();
  /**
   * <pre>
   * The intent that matched the conversational query. Some, not
   * all fields are filled in this message, including but not limited to:
   * &lt;code&gt;name&lt;/code&gt;, &lt;code&gt;display_name&lt;/code&gt; and &lt;code&gt;webhook_state&lt;/code&gt;.
   * </pre>
   *
   * <code>.ondewo.nlu.Intent intent = 11;</code>
   */
  ondewo.nlu.IntentOuterClass.IntentOrBuilder getIntentOrBuilder();

  /**
   * <pre>
   * The intent detection confidence. Values range from 0.0
   * (completely uncertain) to 1.0 (completely certain).
   * </pre>
   *
   * <code>float intent_detection_confidence = 12;</code>
   * @return The intentDetectionConfidence.
   */
  float getIntentDetectionConfidence();

  /**
   * <pre>
   * The user input gets pre-processed by spelling correction, stop word removal etc. This property holds
   * the string that is passed to the entity recognition and intent detection
   * </pre>
   *
   * <code>string query_text_original = 13;</code>
   * @return The queryTextOriginal.
   */
  java.lang.String getQueryTextOriginal();
  /**
   * <pre>
   * The user input gets pre-processed by spelling correction, stop word removal etc. This property holds
   * the string that is passed to the entity recognition and intent detection
   * </pre>
   *
   * <code>string query_text_original = 13;</code>
   * @return The bytes for queryTextOriginal.
   */
  com.google.protobuf.ByteString
      getQueryTextOriginalBytes();

  /**
   * <pre>
   * The free-form diagnostic info. For example, this field
   * could contain webhook call latency.
   * </pre>
   *
   * <code>.google.protobuf.Struct diagnostic_info = 14;</code>
   * @return Whether the diagnosticInfo field is set.
   */
  boolean hasDiagnosticInfo();
  /**
   * <pre>
   * The free-form diagnostic info. For example, this field
   * could contain webhook call latency.
   * </pre>
   *
   * <code>.google.protobuf.Struct diagnostic_info = 14;</code>
   * @return The diagnosticInfo.
   */
  com.google.protobuf.Struct getDiagnosticInfo();
  /**
   * <pre>
   * The free-form diagnostic info. For example, this field
   * could contain webhook call latency.
   * </pre>
   *
   * <code>.google.protobuf.Struct diagnostic_info = 14;</code>
   */
  com.google.protobuf.StructOrBuilder getDiagnosticInfoOrBuilder();

  /**
   * <pre>
   * The language that was triggered during intent detection.
   * See &lt;a href="https://dialogflow.com/docs/reference/language"&gt;Language Support&lt;/a&gt;
   * for a list of the currently supported language codes.
   * </pre>
   *
   * <code>string language_code = 15;</code>
   * @return The languageCode.
   */
  java.lang.String getLanguageCode();
  /**
   * <pre>
   * The language that was triggered during intent detection.
   * See &lt;a href="https://dialogflow.com/docs/reference/language"&gt;Language Support&lt;/a&gt;
   * for a list of the currently supported language codes.
   * </pre>
   *
   * <code>string language_code = 15;</code>
   * @return The bytes for languageCode.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <pre>
   * Generated or attached files, e.g., llm generates a picture or file attachment
   * </pre>
   *
   * <code>repeated .ondewo.nlu.FileResource file_resources = 16;</code>
   */
  java.util.List<com.ondewo.nlu.FileResource> 
      getFileResourcesList();
  /**
   * <pre>
   * Generated or attached files, e.g., llm generates a picture or file attachment
   * </pre>
   *
   * <code>repeated .ondewo.nlu.FileResource file_resources = 16;</code>
   */
  com.ondewo.nlu.FileResource getFileResources(int index);
  /**
   * <pre>
   * Generated or attached files, e.g., llm generates a picture or file attachment
   * </pre>
   *
   * <code>repeated .ondewo.nlu.FileResource file_resources = 16;</code>
   */
  int getFileResourcesCount();
  /**
   * <pre>
   * Generated or attached files, e.g., llm generates a picture or file attachment
   * </pre>
   *
   * <code>repeated .ondewo.nlu.FileResource file_resources = 16;</code>
   */
  java.util.List<? extends com.ondewo.nlu.FileResourceOrBuilder> 
      getFileResourcesOrBuilderList();
  /**
   * <pre>
   * Generated or attached files, e.g., llm generates a picture or file attachment
   * </pre>
   *
   * <code>repeated .ondewo.nlu.FileResource file_resources = 16;</code>
   */
  com.ondewo.nlu.FileResourceOrBuilder getFileResourcesOrBuilder(
      int index);

  /**
   * <pre>
   * Aggregated LLM telemetry (tokens, tool calls, thinking) for this turn.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTelemetryReport llm_telemetry_report = 17;</code>
   * @return Whether the llmTelemetryReport field is set.
   */
  boolean hasLlmTelemetryReport();
  /**
   * <pre>
   * Aggregated LLM telemetry (tokens, tool calls, thinking) for this turn.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTelemetryReport llm_telemetry_report = 17;</code>
   * @return The llmTelemetryReport.
   */
  com.ondewo.nlu.LlmTelemetryReport getLlmTelemetryReport();
  /**
   * <pre>
   * Aggregated LLM telemetry (tokens, tool calls, thinking) for this turn.
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTelemetryReport llm_telemetry_report = 17;</code>
   */
  com.ondewo.nlu.LlmTelemetryReportOrBuilder getLlmTelemetryReportOrBuilder();

  /**
   * <pre>
   * Source chunks the answer cited via in-text &lt;code&gt;[ID:N]&lt;/code&gt; markers, documents. Empty when the turn was not answered from a RAG dataset.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.ReferencedChunk referenced_chunks = 18;</code>
   */
  java.util.List<com.ondewo.nlu.ReferencedChunk> 
      getReferencedChunksList();
  /**
   * <pre>
   * Source chunks the answer cited via in-text &lt;code&gt;[ID:N]&lt;/code&gt; markers, documents. Empty when the turn was not answered from a RAG dataset.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.ReferencedChunk referenced_chunks = 18;</code>
   */
  com.ondewo.nlu.ReferencedChunk getReferencedChunks(int index);
  /**
   * <pre>
   * Source chunks the answer cited via in-text &lt;code&gt;[ID:N]&lt;/code&gt; markers, documents. Empty when the turn was not answered from a RAG dataset.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.ReferencedChunk referenced_chunks = 18;</code>
   */
  int getReferencedChunksCount();
  /**
   * <pre>
   * Source chunks the answer cited via in-text &lt;code&gt;[ID:N]&lt;/code&gt; markers, documents. Empty when the turn was not answered from a RAG dataset.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.ReferencedChunk referenced_chunks = 18;</code>
   */
  java.util.List<? extends com.ondewo.nlu.ReferencedChunkOrBuilder> 
      getReferencedChunksOrBuilderList();
  /**
   * <pre>
   * Source chunks the answer cited via in-text &lt;code&gt;[ID:N]&lt;/code&gt; markers, documents. Empty when the turn was not answered from a RAG dataset.
   * </pre>
   *
   * <code>repeated .ondewo.nlu.ReferencedChunk referenced_chunks = 18;</code>
   */
  com.ondewo.nlu.ReferencedChunkOrBuilder getReferencedChunksOrBuilder(
      int index);
}
