// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface SessionStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.SessionStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier of the session step.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;/sessionsteps/&amp;lt;session_step_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The unique identifier of the session step.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/sessions/&amp;lt;session_uuid&amp;gt;/sessionsteps/&amp;lt;session_step_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The detect intent request of the session step
   * </pre>
   *
   * <code>.ondewo.nlu.DetectIntentRequest detect_intent_request = 2;</code>
   * @return Whether the detectIntentRequest field is set.
   */
  boolean hasDetectIntentRequest();
  /**
   * <pre>
   * The detect intent request of the session step
   * </pre>
   *
   * <code>.ondewo.nlu.DetectIntentRequest detect_intent_request = 2;</code>
   * @return The detectIntentRequest.
   */
  com.ondewo.nlu.DetectIntentRequest getDetectIntentRequest();
  /**
   * <pre>
   * The detect intent request of the session step
   * </pre>
   *
   * <code>.ondewo.nlu.DetectIntentRequest detect_intent_request = 2;</code>
   */
  com.ondewo.nlu.DetectIntentRequestOrBuilder getDetectIntentRequestOrBuilder();

  /**
   * <pre>
   * The detect intent response  of the session step
   * </pre>
   *
   * <code>.ondewo.nlu.DetectIntentResponse detect_intent_response = 3;</code>
   * @return Whether the detectIntentResponse field is set.
   */
  boolean hasDetectIntentResponse();
  /**
   * <pre>
   * The detect intent response  of the session step
   * </pre>
   *
   * <code>.ondewo.nlu.DetectIntentResponse detect_intent_response = 3;</code>
   * @return The detectIntentResponse.
   */
  com.ondewo.nlu.DetectIntentResponse getDetectIntentResponse();
  /**
   * <pre>
   * The detect intent response  of the session step
   * </pre>
   *
   * <code>.ondewo.nlu.DetectIntentResponse detect_intent_response = 3;</code>
   */
  com.ondewo.nlu.DetectIntentResponseOrBuilder getDetectIntentResponseOrBuilder();

  /**
   * <pre>
   * The contexts which were active at the beginning of this step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context contexts = 4;</code>
   */
  java.util.List<com.ondewo.nlu.Context> 
      getContextsList();
  /**
   * <pre>
   * The contexts which were active at the beginning of this step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context contexts = 4;</code>
   */
  com.ondewo.nlu.Context getContexts(int index);
  /**
   * <pre>
   * The contexts which were active at the beginning of this step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context contexts = 4;</code>
   */
  int getContextsCount();
  /**
   * <pre>
   * The contexts which were active at the beginning of this step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context contexts = 4;</code>
   */
  java.util.List<? extends com.ondewo.nlu.ContextOrBuilder> 
      getContextsOrBuilderList();
  /**
   * <pre>
   * The contexts which were active at the beginning of this step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.Context contexts = 4;</code>
   */
  com.ondewo.nlu.ContextOrBuilder getContextsOrBuilder(
      int index);

  /**
   * <pre>
   * Timestamp of session step
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * Timestamp of session step
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * Timestamp of session step
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Creation date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 7;</code>
   * @return Whether the modifiedAt field is set.
   */
  boolean hasModifiedAt();
  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 7;</code>
   * @return The modifiedAt.
   */
  com.google.protobuf.Timestamp getModifiedAt();
  /**
   * <pre>
   * Modification date and time. Read-only field.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedAtOrBuilder();

  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string created_by = 8;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string created_by = 8;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string modified_by = 9;</code>
   * @return The modifiedBy.
   */
  java.lang.String getModifiedBy();
  /**
   * <pre>
   * User id in form of a valid UUID.
   * </pre>
   *
   * <code>string modified_by = 9;</code>
   * @return The bytes for modifiedBy.
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();

  /**
   * <pre>
   * audio file resources associated with the session step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 10;</code>
   */
  java.util.List<com.ondewo.nlu.AudioFileResource> 
      getAudioFileResourcesList();
  /**
   * <pre>
   * audio file resources associated with the session step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 10;</code>
   */
  com.ondewo.nlu.AudioFileResource getAudioFileResources(int index);
  /**
   * <pre>
   * audio file resources associated with the session step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 10;</code>
   */
  int getAudioFileResourcesCount();
  /**
   * <pre>
   * audio file resources associated with the session step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 10;</code>
   */
  java.util.List<? extends com.ondewo.nlu.AudioFileResourceOrBuilder> 
      getAudioFileResourcesOrBuilderList();
  /**
   * <pre>
   * audio file resources associated with the session step
   * </pre>
   *
   * <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 10;</code>
   */
  com.ondewo.nlu.AudioFileResourceOrBuilder getAudioFileResourcesOrBuilder(
      int index);

  /**
   * <pre>
   * Aggregated LLM telemetry for this step (one entry per LLM invocation,
   * plus turn-level totals).
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTelemetryReport llm_telemetry_report = 11;</code>
   * @return Whether the llmTelemetryReport field is set.
   */
  boolean hasLlmTelemetryReport();
  /**
   * <pre>
   * Aggregated LLM telemetry for this step (one entry per LLM invocation,
   * plus turn-level totals).
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTelemetryReport llm_telemetry_report = 11;</code>
   * @return The llmTelemetryReport.
   */
  com.ondewo.nlu.LlmTelemetryReport getLlmTelemetryReport();
  /**
   * <pre>
   * Aggregated LLM telemetry for this step (one entry per LLM invocation,
   * plus turn-level totals).
   * </pre>
   *
   * <code>.ondewo.nlu.LlmTelemetryReport llm_telemetry_report = 11;</code>
   */
  com.ondewo.nlu.LlmTelemetryReportOrBuilder getLlmTelemetryReportOrBuilder();
}
