// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/common.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * Message for streaming notifications in real time via
 * &lt;a href="index.html#ondewo.nlu.Users.StreamNotifications"&gt;Users.StreamNotifications&lt;/a&gt;.
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.StreamNotificationsRequest}
 */
@com.google.protobuf.Generated
public final class StreamNotificationsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.StreamNotificationsRequest)
    StreamNotificationsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      StreamNotificationsRequest.class.getName());
  }
  // Use StreamNotificationsRequest.newBuilder() to construct.
  private StreamNotificationsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StreamNotificationsRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.CommonProto.internal_static_ondewo_nlu_StreamNotificationsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.CommonProto.internal_static_ondewo_nlu_StreamNotificationsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.StreamNotificationsRequest.class, com.ondewo.nlu.StreamNotificationsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int NOTIFICATION_FILTER_FIELD_NUMBER = 1;
  private com.ondewo.nlu.NotificationFilter notificationFilter_;
  /**
   * <pre>
   * Optional filter to narrow the stream down to specific notifications (same semantics as
   * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
   * The caller is always additionally scoped to their own notifications server-side.
   * </pre>
   *
   * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
   * @return Whether the notificationFilter field is set.
   */
  @java.lang.Override
  public boolean hasNotificationFilter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional filter to narrow the stream down to specific notifications (same semantics as
   * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
   * The caller is always additionally scoped to their own notifications server-side.
   * </pre>
   *
   * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
   * @return The notificationFilter.
   */
  @java.lang.Override
  public com.ondewo.nlu.NotificationFilter getNotificationFilter() {
    return notificationFilter_ == null ? com.ondewo.nlu.NotificationFilter.getDefaultInstance() : notificationFilter_;
  }
  /**
   * <pre>
   * Optional filter to narrow the stream down to specific notifications (same semantics as
   * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
   * The caller is always additionally scoped to their own notifications server-side.
   * </pre>
   *
   * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.NotificationFilterOrBuilder getNotificationFilterOrBuilder() {
    return notificationFilter_ == null ? com.ondewo.nlu.NotificationFilter.getDefaultInstance() : notificationFilter_;
  }

  public static final int INCLUDE_EXISTING_FIELD_NUMBER = 2;
  private boolean includeExisting_ = false;
  /**
   * <pre>
   * When true, the currently-stored matching notifications are replayed first (oldest first) before the
   * stream switches to pushing only newly-created notifications. When false (the default) only
   * notifications created after the stream opened are pushed.
   * </pre>
   *
   * <code>bool include_existing = 2;</code>
   * @return The includeExisting.
   */
  @java.lang.Override
  public boolean getIncludeExisting() {
    return includeExisting_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getNotificationFilter());
    }
    if (includeExisting_ != false) {
      output.writeBool(2, includeExisting_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNotificationFilter());
    }
    if (includeExisting_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, includeExisting_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.StreamNotificationsRequest)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.StreamNotificationsRequest other = (com.ondewo.nlu.StreamNotificationsRequest) obj;

    if (hasNotificationFilter() != other.hasNotificationFilter()) return false;
    if (hasNotificationFilter()) {
      if (!getNotificationFilter()
          .equals(other.getNotificationFilter())) return false;
    }
    if (getIncludeExisting()
        != other.getIncludeExisting()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNotificationFilter()) {
      hash = (37 * hash) + NOTIFICATION_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getNotificationFilter().hashCode();
    }
    hash = (37 * hash) + INCLUDE_EXISTING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeExisting());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.StreamNotificationsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.StreamNotificationsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.StreamNotificationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.StreamNotificationsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message for streaming notifications in real time via
   * &lt;a href="index.html#ondewo.nlu.Users.StreamNotifications"&gt;Users.StreamNotifications&lt;/a&gt;.
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.StreamNotificationsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.StreamNotificationsRequest)
      com.ondewo.nlu.StreamNotificationsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.CommonProto.internal_static_ondewo_nlu_StreamNotificationsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.CommonProto.internal_static_ondewo_nlu_StreamNotificationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.StreamNotificationsRequest.class, com.ondewo.nlu.StreamNotificationsRequest.Builder.class);
    }

    // Construct using com.ondewo.nlu.StreamNotificationsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetNotificationFilterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      notificationFilter_ = null;
      if (notificationFilterBuilder_ != null) {
        notificationFilterBuilder_.dispose();
        notificationFilterBuilder_ = null;
      }
      includeExisting_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.CommonProto.internal_static_ondewo_nlu_StreamNotificationsRequest_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.StreamNotificationsRequest getDefaultInstanceForType() {
      return com.ondewo.nlu.StreamNotificationsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.StreamNotificationsRequest build() {
      com.ondewo.nlu.StreamNotificationsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.StreamNotificationsRequest buildPartial() {
      com.ondewo.nlu.StreamNotificationsRequest result = new com.ondewo.nlu.StreamNotificationsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.StreamNotificationsRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.notificationFilter_ = notificationFilterBuilder_ == null
            ? notificationFilter_
            : notificationFilterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.includeExisting_ = includeExisting_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.StreamNotificationsRequest) {
        return mergeFrom((com.ondewo.nlu.StreamNotificationsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.StreamNotificationsRequest other) {
      if (other == com.ondewo.nlu.StreamNotificationsRequest.getDefaultInstance()) return this;
      if (other.hasNotificationFilter()) {
        mergeNotificationFilter(other.getNotificationFilter());
      }
      if (other.getIncludeExisting() != false) {
        setIncludeExisting(other.getIncludeExisting());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetNotificationFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              includeExisting_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.ondewo.nlu.NotificationFilter notificationFilter_;
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.NotificationFilter, com.ondewo.nlu.NotificationFilter.Builder, com.ondewo.nlu.NotificationFilterOrBuilder> notificationFilterBuilder_;
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     * @return Whether the notificationFilter field is set.
     */
    public boolean hasNotificationFilter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     * @return The notificationFilter.
     */
    public com.ondewo.nlu.NotificationFilter getNotificationFilter() {
      if (notificationFilterBuilder_ == null) {
        return notificationFilter_ == null ? com.ondewo.nlu.NotificationFilter.getDefaultInstance() : notificationFilter_;
      } else {
        return notificationFilterBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    public Builder setNotificationFilter(com.ondewo.nlu.NotificationFilter value) {
      if (notificationFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        notificationFilter_ = value;
      } else {
        notificationFilterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    public Builder setNotificationFilter(
        com.ondewo.nlu.NotificationFilter.Builder builderForValue) {
      if (notificationFilterBuilder_ == null) {
        notificationFilter_ = builderForValue.build();
      } else {
        notificationFilterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    public Builder mergeNotificationFilter(com.ondewo.nlu.NotificationFilter value) {
      if (notificationFilterBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          notificationFilter_ != null &&
          notificationFilter_ != com.ondewo.nlu.NotificationFilter.getDefaultInstance()) {
          getNotificationFilterBuilder().mergeFrom(value);
        } else {
          notificationFilter_ = value;
        }
      } else {
        notificationFilterBuilder_.mergeFrom(value);
      }
      if (notificationFilter_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    public Builder clearNotificationFilter() {
      bitField0_ = (bitField0_ & ~0x00000001);
      notificationFilter_ = null;
      if (notificationFilterBuilder_ != null) {
        notificationFilterBuilder_.dispose();
        notificationFilterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    public com.ondewo.nlu.NotificationFilter.Builder getNotificationFilterBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetNotificationFilterFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    public com.ondewo.nlu.NotificationFilterOrBuilder getNotificationFilterOrBuilder() {
      if (notificationFilterBuilder_ != null) {
        return notificationFilterBuilder_.getMessageOrBuilder();
      } else {
        return notificationFilter_ == null ?
            com.ondewo.nlu.NotificationFilter.getDefaultInstance() : notificationFilter_;
      }
    }
    /**
     * <pre>
     * Optional filter to narrow the stream down to specific notifications (same semantics as
     * &lt;a href="index.html#ondewo.nlu.NotificationFilter"&gt;NotificationFilter&lt;/a&gt; used by ListNotifications).
     * The caller is always additionally scoped to their own notifications server-side.
     * </pre>
     *
     * <code>.ondewo.nlu.NotificationFilter notification_filter = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.NotificationFilter, com.ondewo.nlu.NotificationFilter.Builder, com.ondewo.nlu.NotificationFilterOrBuilder> 
        internalGetNotificationFilterFieldBuilder() {
      if (notificationFilterBuilder_ == null) {
        notificationFilterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.ondewo.nlu.NotificationFilter, com.ondewo.nlu.NotificationFilter.Builder, com.ondewo.nlu.NotificationFilterOrBuilder>(
                getNotificationFilter(),
                getParentForChildren(),
                isClean());
        notificationFilter_ = null;
      }
      return notificationFilterBuilder_;
    }

    private boolean includeExisting_ ;
    /**
     * <pre>
     * When true, the currently-stored matching notifications are replayed first (oldest first) before the
     * stream switches to pushing only newly-created notifications. When false (the default) only
     * notifications created after the stream opened are pushed.
     * </pre>
     *
     * <code>bool include_existing = 2;</code>
     * @return The includeExisting.
     */
    @java.lang.Override
    public boolean getIncludeExisting() {
      return includeExisting_;
    }
    /**
     * <pre>
     * When true, the currently-stored matching notifications are replayed first (oldest first) before the
     * stream switches to pushing only newly-created notifications. When false (the default) only
     * notifications created after the stream opened are pushed.
     * </pre>
     *
     * <code>bool include_existing = 2;</code>
     * @param value The includeExisting to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeExisting(boolean value) {

      includeExisting_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When true, the currently-stored matching notifications are replayed first (oldest first) before the
     * stream switches to pushing only newly-created notifications. When false (the default) only
     * notifications created after the stream opened are pushed.
     * </pre>
     *
     * <code>bool include_existing = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeExisting() {
      bitField0_ = (bitField0_ & ~0x00000002);
      includeExisting_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.StreamNotificationsRequest)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.StreamNotificationsRequest)
  private static final com.ondewo.nlu.StreamNotificationsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.StreamNotificationsRequest();
  }

  public static com.ondewo.nlu.StreamNotificationsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamNotificationsRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamNotificationsRequest>() {
    @java.lang.Override
    public StreamNotificationsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamNotificationsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamNotificationsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.StreamNotificationsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

