// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * Contains a speech recognition result corresponding to a portion of the audio that is currently being processed or an indication that this is the end of the single requested utterance.
 *
 * Example:
 *
 * 1.  transcript: &amp;quot;tube&amp;quot;
 *
 * 2.  transcript: &amp;quot;to be a&amp;quot;
 *
 * 3.  transcript: &amp;quot;to be&amp;quot;
 *
 * 4.  transcript: &amp;quot;to be or not to be&amp;quot;
 * is_final: true
 *
 * 5.  transcript: &amp;quot; that&amp;apos;s&amp;quot;
 *
 * 6.  transcript: &amp;quot; that is&amp;quot;
 *
 * 7.  recognition_event_type: &lt;code&gt;RECOGNITION_EVENT_END_OF_SINGLE_UTTERANCE&lt;/code&gt;
 *
 * 8.  transcript: &amp;quot; that is the question&amp;quot;
 * is_final: true
 *
 * Only two of the responses contain final results (#4 and #8 indicated by &lt;code&gt;is_final: true&lt;/code&gt;). Concatenating these generates the full transcript: &lt;code&gt;"to be or not to be that is the question"&lt;/code&gt;.
 *
 * In each response we populate:
 *
 * &lt;ul&gt;
 * &lt;li&gt;for &lt;code&gt;MESSAGE_TYPE_TRANSCRIPT&lt;/code&gt;: &lt;code&gt;transcript&lt;/code&gt; and possibly &lt;code&gt;is_final&lt;/code&gt;.&lt;/li&gt;
 * &lt;li&gt;for &lt;code&gt;MESSAGE_TYPE_END_OF_SINGLE_UTTERANCE&lt;/code&gt;: only &lt;code&gt;event_type&lt;/code&gt;.&lt;/li&gt;
 * &lt;/ul&gt;
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.StreamingRecognitionResult}
 */
@com.google.protobuf.Generated
public final class StreamingRecognitionResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.StreamingRecognitionResult)
    StreamingRecognitionResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      StreamingRecognitionResult.class.getName());
  }
  // Use StreamingRecognitionResult.newBuilder() to construct.
  private StreamingRecognitionResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StreamingRecognitionResult() {
    messageType_ = 0;
    transcript_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_StreamingRecognitionResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_StreamingRecognitionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.StreamingRecognitionResult.class, com.ondewo.nlu.StreamingRecognitionResult.Builder.class);
  }

  /**
   * <pre>
   * Type of the response message.
   * </pre>
   *
   * Protobuf enum {@code ondewo.nlu.StreamingRecognitionResult.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Not specified. Should never be used.
     * </pre>
     *
     * <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
     */
    MESSAGE_TYPE_UNSPECIFIED(0),
    /**
     * <pre>
     * Message contains a (possibly partial) transcript.
     * </pre>
     *
     * <code>TRANSCRIPT = 1;</code>
     */
    TRANSCRIPT(1),
    /**
     * <pre>
     * Event indicates that the server has detected the end of the user&amp;apos;s speech
     * utterance and expects no additional speech. Therefore, the server will
     * not process additional audio (although it may subsequently return
     * additional results). The client should stop sending additional audio
     * data, half-close the gRPC connection, and wait for any additional results
     * until the server closes the gRPC connection. This message is only sent if
     * &lt;code&gt;single_utterance&lt;/code&gt; was set to &lt;code&gt;true&lt;/code&gt;, and is not used otherwise.
     * </pre>
     *
     * <code>END_OF_SINGLE_UTTERANCE = 2;</code>
     */
    END_OF_SINGLE_UTTERANCE(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        MessageType.class.getName());
    }
    /**
     * <pre>
     * Not specified. Should never be used.
     * </pre>
     *
     * <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int MESSAGE_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * Message contains a (possibly partial) transcript.
     * </pre>
     *
     * <code>TRANSCRIPT = 1;</code>
     */
    public static final int TRANSCRIPT_VALUE = 1;
    /**
     * <pre>
     * Event indicates that the server has detected the end of the user&amp;apos;s speech
     * utterance and expects no additional speech. Therefore, the server will
     * not process additional audio (although it may subsequently return
     * additional results). The client should stop sending additional audio
     * data, half-close the gRPC connection, and wait for any additional results
     * until the server closes the gRPC connection. This message is only sent if
     * &lt;code&gt;single_utterance&lt;/code&gt; was set to &lt;code&gt;true&lt;/code&gt;, and is not used otherwise.
     * </pre>
     *
     * <code>END_OF_SINGLE_UTTERANCE = 2;</code>
     */
    public static final int END_OF_SINGLE_UTTERANCE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE_TYPE_UNSPECIFIED;
        case 1: return TRANSCRIPT;
        case 2: return END_OF_SINGLE_UTTERANCE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ondewo.nlu.StreamingRecognitionResult.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ondewo.nlu.StreamingRecognitionResult.MessageType)
  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
  private int messageType_ = 0;
  /**
   * <pre>
   * Type of the result message.
   * </pre>
   *
   * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <pre>
   * Type of the result message.
   * </pre>
   *
   * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override public com.ondewo.nlu.StreamingRecognitionResult.MessageType getMessageType() {
    com.ondewo.nlu.StreamingRecognitionResult.MessageType result = com.ondewo.nlu.StreamingRecognitionResult.MessageType.forNumber(messageType_);
    return result == null ? com.ondewo.nlu.StreamingRecognitionResult.MessageType.UNRECOGNIZED : result;
  }

  public static final int TRANSCRIPT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transcript_ = "";
  /**
   * <pre>
   * Transcript text representing the words that the user spoke.
   * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
   * </pre>
   *
   * <code>string transcript = 2;</code>
   * @return The transcript.
   */
  @java.lang.Override
  public java.lang.String getTranscript() {
    java.lang.Object ref = transcript_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transcript_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Transcript text representing the words that the user spoke.
   * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
   * </pre>
   *
   * <code>string transcript = 2;</code>
   * @return The bytes for transcript.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTranscriptBytes() {
    java.lang.Object ref = transcript_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transcript_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_FINAL_FIELD_NUMBER = 3;
  private boolean isFinal_ = false;
  /**
   * <pre>
   * The default of 0.0 is a sentinel value indicating &lt;code&gt;confidence&lt;/code&gt; was not set.
   * If &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;StreamingRecognitionResult&lt;/code&gt; represents an
   * interim result that may change. If &lt;code&gt;true&lt;/code&gt;, the recognizer will not return
   * any further hypotheses about this piece of the audio. May only be populated
   * for &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
   * </pre>
   *
   * <code>bool is_final = 3;</code>
   * @return The isFinal.
   */
  @java.lang.Override
  public boolean getIsFinal() {
    return isFinal_;
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 4;
  private float confidence_ = 0F;
  /**
   * <pre>
   * The Speech confidence between 0.0 and 1.0 for the current portion of audio.
   * A higher number indicates an estimated greater likelihood that the
   * recognized words are correct. The default of 0.0 is a sentinel value
   * indicating that confidence was not set.
   *
   * This field is typically only provided if &lt;code&gt;is_final&lt;/code&gt; is true and you should
   * not rely on it being accurate or even set.
   * </pre>
   *
   * <code>float confidence = 4;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != com.ondewo.nlu.StreamingRecognitionResult.MessageType.MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, messageType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transcript_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, transcript_);
    }
    if (isFinal_ != false) {
      output.writeBool(3, isFinal_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      output.writeFloat(4, confidence_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != com.ondewo.nlu.StreamingRecognitionResult.MessageType.MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transcript_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, transcript_);
    }
    if (isFinal_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isFinal_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, confidence_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.StreamingRecognitionResult)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.StreamingRecognitionResult other = (com.ondewo.nlu.StreamingRecognitionResult) obj;

    if (messageType_ != other.messageType_) return false;
    if (!getTranscript()
        .equals(other.getTranscript())) return false;
    if (getIsFinal()
        != other.getIsFinal()) return false;
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    hash = (37 * hash) + TRANSCRIPT_FIELD_NUMBER;
    hash = (53 * hash) + getTranscript().hashCode();
    hash = (37 * hash) + IS_FINAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFinal());
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.StreamingRecognitionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.StreamingRecognitionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.StreamingRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.StreamingRecognitionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Contains a speech recognition result corresponding to a portion of the audio that is currently being processed or an indication that this is the end of the single requested utterance.
   *
   * Example:
   *
   * 1.  transcript: &amp;quot;tube&amp;quot;
   *
   * 2.  transcript: &amp;quot;to be a&amp;quot;
   *
   * 3.  transcript: &amp;quot;to be&amp;quot;
   *
   * 4.  transcript: &amp;quot;to be or not to be&amp;quot;
   * is_final: true
   *
   * 5.  transcript: &amp;quot; that&amp;apos;s&amp;quot;
   *
   * 6.  transcript: &amp;quot; that is&amp;quot;
   *
   * 7.  recognition_event_type: &lt;code&gt;RECOGNITION_EVENT_END_OF_SINGLE_UTTERANCE&lt;/code&gt;
   *
   * 8.  transcript: &amp;quot; that is the question&amp;quot;
   * is_final: true
   *
   * Only two of the responses contain final results (#4 and #8 indicated by &lt;code&gt;is_final: true&lt;/code&gt;). Concatenating these generates the full transcript: &lt;code&gt;"to be or not to be that is the question"&lt;/code&gt;.
   *
   * In each response we populate:
   *
   * &lt;ul&gt;
   * &lt;li&gt;for &lt;code&gt;MESSAGE_TYPE_TRANSCRIPT&lt;/code&gt;: &lt;code&gt;transcript&lt;/code&gt; and possibly &lt;code&gt;is_final&lt;/code&gt;.&lt;/li&gt;
   * &lt;li&gt;for &lt;code&gt;MESSAGE_TYPE_END_OF_SINGLE_UTTERANCE&lt;/code&gt;: only &lt;code&gt;event_type&lt;/code&gt;.&lt;/li&gt;
   * &lt;/ul&gt;
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.StreamingRecognitionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.StreamingRecognitionResult)
      com.ondewo.nlu.StreamingRecognitionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_StreamingRecognitionResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_StreamingRecognitionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.StreamingRecognitionResult.class, com.ondewo.nlu.StreamingRecognitionResult.Builder.class);
    }

    // Construct using com.ondewo.nlu.StreamingRecognitionResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageType_ = 0;
      transcript_ = "";
      isFinal_ = false;
      confidence_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_StreamingRecognitionResult_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.StreamingRecognitionResult getDefaultInstanceForType() {
      return com.ondewo.nlu.StreamingRecognitionResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.StreamingRecognitionResult build() {
      com.ondewo.nlu.StreamingRecognitionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.StreamingRecognitionResult buildPartial() {
      com.ondewo.nlu.StreamingRecognitionResult result = new com.ondewo.nlu.StreamingRecognitionResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.StreamingRecognitionResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageType_ = messageType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.transcript_ = transcript_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isFinal_ = isFinal_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.confidence_ = confidence_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.StreamingRecognitionResult) {
        return mergeFrom((com.ondewo.nlu.StreamingRecognitionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.StreamingRecognitionResult other) {
      if (other == com.ondewo.nlu.StreamingRecognitionResult.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      if (!other.getTranscript().isEmpty()) {
        transcript_ = other.transcript_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getIsFinal() != false) {
        setIsFinal(other.getIsFinal());
      }
      if (java.lang.Float.floatToRawIntBits(other.getConfidence()) != 0) {
        setConfidence(other.getConfidence());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              transcript_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              isFinal_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 37: {
              confidence_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int messageType_ = 0;
    /**
     * <pre>
     * Type of the result message.
     * </pre>
     *
     * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     * Type of the result message.
     * </pre>
     *
     * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      messageType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the result message.
     * </pre>
     *
     * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public com.ondewo.nlu.StreamingRecognitionResult.MessageType getMessageType() {
      com.ondewo.nlu.StreamingRecognitionResult.MessageType result = com.ondewo.nlu.StreamingRecognitionResult.MessageType.forNumber(messageType_);
      return result == null ? com.ondewo.nlu.StreamingRecognitionResult.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Type of the result message.
     * </pre>
     *
     * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(com.ondewo.nlu.StreamingRecognitionResult.MessageType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the result message.
     * </pre>
     *
     * <code>.ondewo.nlu.StreamingRecognitionResult.MessageType message_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object transcript_ = "";
    /**
     * <pre>
     * Transcript text representing the words that the user spoke.
     * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>string transcript = 2;</code>
     * @return The transcript.
     */
    public java.lang.String getTranscript() {
      java.lang.Object ref = transcript_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transcript_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Transcript text representing the words that the user spoke.
     * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>string transcript = 2;</code>
     * @return The bytes for transcript.
     */
    public com.google.protobuf.ByteString
        getTranscriptBytes() {
      java.lang.Object ref = transcript_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transcript_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Transcript text representing the words that the user spoke.
     * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>string transcript = 2;</code>
     * @param value The transcript to set.
     * @return This builder for chaining.
     */
    public Builder setTranscript(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transcript_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transcript text representing the words that the user spoke.
     * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>string transcript = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranscript() {
      transcript_ = getDefaultInstance().getTranscript();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transcript text representing the words that the user spoke.
     * Populated if and only if &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>string transcript = 2;</code>
     * @param value The bytes for transcript to set.
     * @return This builder for chaining.
     */
    public Builder setTranscriptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transcript_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean isFinal_ ;
    /**
     * <pre>
     * The default of 0.0 is a sentinel value indicating &lt;code&gt;confidence&lt;/code&gt; was not set.
     * If &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;StreamingRecognitionResult&lt;/code&gt; represents an
     * interim result that may change. If &lt;code&gt;true&lt;/code&gt;, the recognizer will not return
     * any further hypotheses about this piece of the audio. May only be populated
     * for &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>bool is_final = 3;</code>
     * @return The isFinal.
     */
    @java.lang.Override
    public boolean getIsFinal() {
      return isFinal_;
    }
    /**
     * <pre>
     * The default of 0.0 is a sentinel value indicating &lt;code&gt;confidence&lt;/code&gt; was not set.
     * If &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;StreamingRecognitionResult&lt;/code&gt; represents an
     * interim result that may change. If &lt;code&gt;true&lt;/code&gt;, the recognizer will not return
     * any further hypotheses about this piece of the audio. May only be populated
     * for &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>bool is_final = 3;</code>
     * @param value The isFinal to set.
     * @return This builder for chaining.
     */
    public Builder setIsFinal(boolean value) {

      isFinal_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The default of 0.0 is a sentinel value indicating &lt;code&gt;confidence&lt;/code&gt; was not set.
     * If &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;StreamingRecognitionResult&lt;/code&gt; represents an
     * interim result that may change. If &lt;code&gt;true&lt;/code&gt;, the recognizer will not return
     * any further hypotheses about this piece of the audio. May only be populated
     * for &lt;code&gt;event_type&lt;/code&gt; = &lt;code&gt;RECOGNITION_EVENT_TRANSCRIPT&lt;/code&gt;.
     * </pre>
     *
     * <code>bool is_final = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFinal() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isFinal_ = false;
      onChanged();
      return this;
    }

    private float confidence_ ;
    /**
     * <pre>
     * The Speech confidence between 0.0 and 1.0 for the current portion of audio.
     * A higher number indicates an estimated greater likelihood that the
     * recognized words are correct. The default of 0.0 is a sentinel value
     * indicating that confidence was not set.
     *
     * This field is typically only provided if &lt;code&gt;is_final&lt;/code&gt; is true and you should
     * not rely on it being accurate or even set.
     * </pre>
     *
     * <code>float confidence = 4;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <pre>
     * The Speech confidence between 0.0 and 1.0 for the current portion of audio.
     * A higher number indicates an estimated greater likelihood that the
     * recognized words are correct. The default of 0.0 is a sentinel value
     * indicating that confidence was not set.
     *
     * This field is typically only provided if &lt;code&gt;is_final&lt;/code&gt; is true and you should
     * not rely on it being accurate or even set.
     * </pre>
     *
     * <code>float confidence = 4;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {

      confidence_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Speech confidence between 0.0 and 1.0 for the current portion of audio.
     * A higher number indicates an estimated greater likelihood that the
     * recognized words are correct. The default of 0.0 is a sentinel value
     * indicating that confidence was not set.
     *
     * This field is typically only provided if &lt;code&gt;is_final&lt;/code&gt; is true and you should
     * not rely on it being accurate or even set.
     * </pre>
     *
     * <code>float confidence = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      bitField0_ = (bitField0_ & ~0x00000008);
      confidence_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.StreamingRecognitionResult)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.StreamingRecognitionResult)
  private static final com.ondewo.nlu.StreamingRecognitionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.StreamingRecognitionResult();
  }

  public static com.ondewo.nlu.StreamingRecognitionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingRecognitionResult>
      PARSER = new com.google.protobuf.AbstractParser<StreamingRecognitionResult>() {
    @java.lang.Override
    public StreamingRecognitionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamingRecognitionResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamingRecognitionResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.StreamingRecognitionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

