// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * Identifies whether a transcription was produced by an automatic
 * speech-to-text system or by a human annotator.
 * </pre>
 *
 * Protobuf enum {@code ondewo.nlu.TranscriptionType}
 */
@com.google.protobuf.Generated
public enum TranscriptionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Sentinel value when the source of the transcription was not specified.
   * </pre>
   *
   * <code>TRANSCRIPTION_TYPE_UNSPECIFIED = 0;</code>
   */
  TRANSCRIPTION_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * Automatic transcription produced by a speech-to-text system.
   * </pre>
   *
   * <code>TRANSCRIPTION_TYPE_S2T = 1;</code>
   */
  TRANSCRIPTION_TYPE_S2T(1),
  /**
   * <pre>
   * Manual transcription produced by a human annotator.
   * </pre>
   *
   * <code>TRANSCRIPTION_TYPE_HUMAN = 2;</code>
   */
  TRANSCRIPTION_TYPE_HUMAN(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      TranscriptionType.class.getName());
  }
  /**
   * <pre>
   * Sentinel value when the source of the transcription was not specified.
   * </pre>
   *
   * <code>TRANSCRIPTION_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int TRANSCRIPTION_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Automatic transcription produced by a speech-to-text system.
   * </pre>
   *
   * <code>TRANSCRIPTION_TYPE_S2T = 1;</code>
   */
  public static final int TRANSCRIPTION_TYPE_S2T_VALUE = 1;
  /**
   * <pre>
   * Manual transcription produced by a human annotator.
   * </pre>
   *
   * <code>TRANSCRIPTION_TYPE_HUMAN = 2;</code>
   */
  public static final int TRANSCRIPTION_TYPE_HUMAN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TranscriptionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TranscriptionType forNumber(int value) {
    switch (value) {
      case 0: return TRANSCRIPTION_TYPE_UNSPECIFIED;
      case 1: return TRANSCRIPTION_TYPE_S2T;
      case 2: return TRANSCRIPTION_TYPE_HUMAN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TranscriptionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TranscriptionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TranscriptionType>() {
          public TranscriptionType findValueByNumber(int number) {
            return TranscriptionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final TranscriptionType[] VALUES = values();

  public static TranscriptionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TranscriptionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ondewo.nlu.TranscriptionType)
}

