// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * Request to update (revise) an existing feedback.
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.UpdateSessionFeedbackRequest}
 */
@com.google.protobuf.Generated
public final class UpdateSessionFeedbackRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.UpdateSessionFeedbackRequest)
    UpdateSessionFeedbackRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      UpdateSessionFeedbackRequest.class.getName());
  }
  // Use UpdateSessionFeedbackRequest.newBuilder() to construct.
  private UpdateSessionFeedbackRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateSessionFeedbackRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionFeedbackRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionFeedbackRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.UpdateSessionFeedbackRequest.class, com.ondewo.nlu.UpdateSessionFeedbackRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FEEDBACK_FIELD_NUMBER = 1;
  private com.ondewo.nlu.SessionFeedback feedback_;
  /**
   * <pre>
   * The feedback to update; feedback.name identifies the record.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
   * @return Whether the feedback field is set.
   */
  @java.lang.Override
  public boolean hasFeedback() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The feedback to update; feedback.name identifies the record.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
   * @return The feedback.
   */
  @java.lang.Override
  public com.ondewo.nlu.SessionFeedback getFeedback() {
    return feedback_ == null ? com.ondewo.nlu.SessionFeedback.getDefaultInstance() : feedback_;
  }
  /**
   * <pre>
   * The feedback to update; feedback.name identifies the record.
   * </pre>
   *
   * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.SessionFeedbackOrBuilder getFeedbackOrBuilder() {
    return feedback_ == null ? com.ondewo.nlu.SessionFeedback.getDefaultInstance() : feedback_;
  }

  public static final int UPDATE_MASK_FIELD_NUMBER = 2;
  private com.google.protobuf.FieldMask updateMask_;
  /**
   * <pre>
   * Optional. The fields of the feedback to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return Whether the updateMask field is set.
   */
  @java.lang.Override
  public boolean hasUpdateMask() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Optional. The fields of the feedback to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return The updateMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getUpdateMask() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }
  /**
   * <pre>
   * Optional. The fields of the feedback to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getFeedback());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getUpdateMask());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFeedback());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdateMask());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.UpdateSessionFeedbackRequest)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.UpdateSessionFeedbackRequest other = (com.ondewo.nlu.UpdateSessionFeedbackRequest) obj;

    if (hasFeedback() != other.hasFeedback()) return false;
    if (hasFeedback()) {
      if (!getFeedback()
          .equals(other.getFeedback())) return false;
    }
    if (hasUpdateMask() != other.hasUpdateMask()) return false;
    if (hasUpdateMask()) {
      if (!getUpdateMask()
          .equals(other.getUpdateMask())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFeedback()) {
      hash = (37 * hash) + FEEDBACK_FIELD_NUMBER;
      hash = (53 * hash) + getFeedback().hashCode();
    }
    if (hasUpdateMask()) {
      hash = (37 * hash) + UPDATE_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateMask().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.UpdateSessionFeedbackRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.UpdateSessionFeedbackRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to update (revise) an existing feedback.
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.UpdateSessionFeedbackRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.UpdateSessionFeedbackRequest)
      com.ondewo.nlu.UpdateSessionFeedbackRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionFeedbackRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionFeedbackRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.UpdateSessionFeedbackRequest.class, com.ondewo.nlu.UpdateSessionFeedbackRequest.Builder.class);
    }

    // Construct using com.ondewo.nlu.UpdateSessionFeedbackRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFeedbackFieldBuilder();
        internalGetUpdateMaskFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      feedback_ = null;
      if (feedbackBuilder_ != null) {
        feedbackBuilder_.dispose();
        feedbackBuilder_ = null;
      }
      updateMask_ = null;
      if (updateMaskBuilder_ != null) {
        updateMaskBuilder_.dispose();
        updateMaskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionFeedbackRequest_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateSessionFeedbackRequest getDefaultInstanceForType() {
      return com.ondewo.nlu.UpdateSessionFeedbackRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateSessionFeedbackRequest build() {
      com.ondewo.nlu.UpdateSessionFeedbackRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateSessionFeedbackRequest buildPartial() {
      com.ondewo.nlu.UpdateSessionFeedbackRequest result = new com.ondewo.nlu.UpdateSessionFeedbackRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.UpdateSessionFeedbackRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.feedback_ = feedbackBuilder_ == null
            ? feedback_
            : feedbackBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.updateMask_ = updateMaskBuilder_ == null
            ? updateMask_
            : updateMaskBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.UpdateSessionFeedbackRequest) {
        return mergeFrom((com.ondewo.nlu.UpdateSessionFeedbackRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.UpdateSessionFeedbackRequest other) {
      if (other == com.ondewo.nlu.UpdateSessionFeedbackRequest.getDefaultInstance()) return this;
      if (other.hasFeedback()) {
        mergeFeedback(other.getFeedback());
      }
      if (other.hasUpdateMask()) {
        mergeUpdateMask(other.getUpdateMask());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetFeedbackFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetUpdateMaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.ondewo.nlu.SessionFeedback feedback_;
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.SessionFeedback, com.ondewo.nlu.SessionFeedback.Builder, com.ondewo.nlu.SessionFeedbackOrBuilder> feedbackBuilder_;
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     * @return Whether the feedback field is set.
     */
    public boolean hasFeedback() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     * @return The feedback.
     */
    public com.ondewo.nlu.SessionFeedback getFeedback() {
      if (feedbackBuilder_ == null) {
        return feedback_ == null ? com.ondewo.nlu.SessionFeedback.getDefaultInstance() : feedback_;
      } else {
        return feedbackBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    public Builder setFeedback(com.ondewo.nlu.SessionFeedback value) {
      if (feedbackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        feedback_ = value;
      } else {
        feedbackBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    public Builder setFeedback(
        com.ondewo.nlu.SessionFeedback.Builder builderForValue) {
      if (feedbackBuilder_ == null) {
        feedback_ = builderForValue.build();
      } else {
        feedbackBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    public Builder mergeFeedback(com.ondewo.nlu.SessionFeedback value) {
      if (feedbackBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          feedback_ != null &&
          feedback_ != com.ondewo.nlu.SessionFeedback.getDefaultInstance()) {
          getFeedbackBuilder().mergeFrom(value);
        } else {
          feedback_ = value;
        }
      } else {
        feedbackBuilder_.mergeFrom(value);
      }
      if (feedback_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    public Builder clearFeedback() {
      bitField0_ = (bitField0_ & ~0x00000001);
      feedback_ = null;
      if (feedbackBuilder_ != null) {
        feedbackBuilder_.dispose();
        feedbackBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    public com.ondewo.nlu.SessionFeedback.Builder getFeedbackBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetFeedbackFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    public com.ondewo.nlu.SessionFeedbackOrBuilder getFeedbackOrBuilder() {
      if (feedbackBuilder_ != null) {
        return feedbackBuilder_.getMessageOrBuilder();
      } else {
        return feedback_ == null ?
            com.ondewo.nlu.SessionFeedback.getDefaultInstance() : feedback_;
      }
    }
    /**
     * <pre>
     * The feedback to update; feedback.name identifies the record.
     * </pre>
     *
     * <code>.ondewo.nlu.SessionFeedback feedback = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.SessionFeedback, com.ondewo.nlu.SessionFeedback.Builder, com.ondewo.nlu.SessionFeedbackOrBuilder> 
        internalGetFeedbackFieldBuilder() {
      if (feedbackBuilder_ == null) {
        feedbackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.ondewo.nlu.SessionFeedback, com.ondewo.nlu.SessionFeedback.Builder, com.ondewo.nlu.SessionFeedbackOrBuilder>(
                getFeedback(),
                getParentForChildren(),
                isClean());
        feedback_ = null;
      }
      return feedbackBuilder_;
    }

    private com.google.protobuf.FieldMask updateMask_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> updateMaskBuilder_;
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return Whether the updateMask field is set.
     */
    public boolean hasUpdateMask() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return The updateMask.
     */
    public com.google.protobuf.FieldMask getUpdateMask() {
      if (updateMaskBuilder_ == null) {
        return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
      } else {
        return updateMaskBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder setUpdateMask(com.google.protobuf.FieldMask value) {
      if (updateMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateMask_ = value;
      } else {
        updateMaskBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder setUpdateMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (updateMaskBuilder_ == null) {
        updateMask_ = builderForValue.build();
      } else {
        updateMaskBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder mergeUpdateMask(com.google.protobuf.FieldMask value) {
      if (updateMaskBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          updateMask_ != null &&
          updateMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
          getUpdateMaskBuilder().mergeFrom(value);
        } else {
          updateMask_ = value;
        }
      } else {
        updateMaskBuilder_.mergeFrom(value);
      }
      if (updateMask_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder clearUpdateMask() {
      bitField0_ = (bitField0_ & ~0x00000002);
      updateMask_ = null;
      if (updateMaskBuilder_ != null) {
        updateMaskBuilder_.dispose();
        updateMaskBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public com.google.protobuf.FieldMask.Builder getUpdateMaskBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetUpdateMaskFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
      if (updateMaskBuilder_ != null) {
        return updateMaskBuilder_.getMessageOrBuilder();
      } else {
        return updateMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
      }
    }
    /**
     * <pre>
     * Optional. The fields of the feedback to update.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        internalGetUpdateMaskFieldBuilder() {
      if (updateMaskBuilder_ == null) {
        updateMaskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getUpdateMask(),
                getParentForChildren(),
                isClean());
        updateMask_ = null;
      }
      return updateMaskBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.UpdateSessionFeedbackRequest)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.UpdateSessionFeedbackRequest)
  private static final com.ondewo.nlu.UpdateSessionFeedbackRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.UpdateSessionFeedbackRequest();
  }

  public static com.ondewo.nlu.UpdateSessionFeedbackRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateSessionFeedbackRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateSessionFeedbackRequest>() {
    @java.lang.Override
    public UpdateSessionFeedbackRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateSessionFeedbackRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateSessionFeedbackRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.UpdateSessionFeedbackRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

