// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/session.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * This message is a request to update a session comment
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.UpdateSessionCommentsRequest}
 */
@com.google.protobuf.Generated
public final class UpdateSessionCommentsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.UpdateSessionCommentsRequest)
    UpdateSessionCommentsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      UpdateSessionCommentsRequest.class.getName());
  }
  // Use UpdateSessionCommentsRequest.newBuilder() to construct.
  private UpdateSessionCommentsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateSessionCommentsRequest() {
    sessionId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionCommentsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionCommentsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.UpdateSessionCommentsRequest.class, com.ondewo.nlu.UpdateSessionCommentsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <pre>
   * The id of the session
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the session
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENT_FIELD_NUMBER = 2;
  private com.ondewo.nlu.Comment comment_;
  /**
   * <pre>
   * The comment of a session to be updated
   * </pre>
   *
   * <code>.ondewo.nlu.Comment comment = 2;</code>
   * @return Whether the comment field is set.
   */
  @java.lang.Override
  public boolean hasComment() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The comment of a session to be updated
   * </pre>
   *
   * <code>.ondewo.nlu.Comment comment = 2;</code>
   * @return The comment.
   */
  @java.lang.Override
  public com.ondewo.nlu.Comment getComment() {
    return comment_ == null ? com.ondewo.nlu.Comment.getDefaultInstance() : comment_;
  }
  /**
   * <pre>
   * The comment of a session to be updated
   * </pre>
   *
   * <code>.ondewo.nlu.Comment comment = 2;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.CommentOrBuilder getCommentOrBuilder() {
    return comment_ == null ? com.ondewo.nlu.Comment.getDefaultInstance() : comment_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getComment());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getComment());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.UpdateSessionCommentsRequest)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.UpdateSessionCommentsRequest other = (com.ondewo.nlu.UpdateSessionCommentsRequest) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (hasComment() != other.hasComment()) return false;
    if (hasComment()) {
      if (!getComment()
          .equals(other.getComment())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    if (hasComment()) {
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.UpdateSessionCommentsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.UpdateSessionCommentsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * This message is a request to update a session comment
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.UpdateSessionCommentsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.UpdateSessionCommentsRequest)
      com.ondewo.nlu.UpdateSessionCommentsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionCommentsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionCommentsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.UpdateSessionCommentsRequest.class, com.ondewo.nlu.UpdateSessionCommentsRequest.Builder.class);
    }

    // Construct using com.ondewo.nlu.UpdateSessionCommentsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCommentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      comment_ = null;
      if (commentBuilder_ != null) {
        commentBuilder_.dispose();
        commentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.SessionProto.internal_static_ondewo_nlu_UpdateSessionCommentsRequest_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateSessionCommentsRequest getDefaultInstanceForType() {
      return com.ondewo.nlu.UpdateSessionCommentsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateSessionCommentsRequest build() {
      com.ondewo.nlu.UpdateSessionCommentsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateSessionCommentsRequest buildPartial() {
      com.ondewo.nlu.UpdateSessionCommentsRequest result = new com.ondewo.nlu.UpdateSessionCommentsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.UpdateSessionCommentsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.comment_ = commentBuilder_ == null
            ? comment_
            : commentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.UpdateSessionCommentsRequest) {
        return mergeFrom((com.ondewo.nlu.UpdateSessionCommentsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.UpdateSessionCommentsRequest other) {
      if (other == com.ondewo.nlu.UpdateSessionCommentsRequest.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasComment()) {
        mergeComment(other.getComment());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetCommentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <pre>
     * The id of the session
     * </pre>
     *
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the session
     * </pre>
     *
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the session
     * </pre>
     *
     * <code>string session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the session
     * </pre>
     *
     * <code>string session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the session
     * </pre>
     *
     * <code>string session_id = 1;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.ondewo.nlu.Comment comment_;
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.Comment, com.ondewo.nlu.Comment.Builder, com.ondewo.nlu.CommentOrBuilder> commentBuilder_;
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     * @return Whether the comment field is set.
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     * @return The comment.
     */
    public com.ondewo.nlu.Comment getComment() {
      if (commentBuilder_ == null) {
        return comment_ == null ? com.ondewo.nlu.Comment.getDefaultInstance() : comment_;
      } else {
        return commentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    public Builder setComment(com.ondewo.nlu.Comment value) {
      if (commentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        comment_ = value;
      } else {
        commentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    public Builder setComment(
        com.ondewo.nlu.Comment.Builder builderForValue) {
      if (commentBuilder_ == null) {
        comment_ = builderForValue.build();
      } else {
        commentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    public Builder mergeComment(com.ondewo.nlu.Comment value) {
      if (commentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          comment_ != null &&
          comment_ != com.ondewo.nlu.Comment.getDefaultInstance()) {
          getCommentBuilder().mergeFrom(value);
        } else {
          comment_ = value;
        }
      } else {
        commentBuilder_.mergeFrom(value);
      }
      if (comment_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    public Builder clearComment() {
      bitField0_ = (bitField0_ & ~0x00000002);
      comment_ = null;
      if (commentBuilder_ != null) {
        commentBuilder_.dispose();
        commentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    public com.ondewo.nlu.Comment.Builder getCommentBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetCommentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    public com.ondewo.nlu.CommentOrBuilder getCommentOrBuilder() {
      if (commentBuilder_ != null) {
        return commentBuilder_.getMessageOrBuilder();
      } else {
        return comment_ == null ?
            com.ondewo.nlu.Comment.getDefaultInstance() : comment_;
      }
    }
    /**
     * <pre>
     * The comment of a session to be updated
     * </pre>
     *
     * <code>.ondewo.nlu.Comment comment = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.Comment, com.ondewo.nlu.Comment.Builder, com.ondewo.nlu.CommentOrBuilder> 
        internalGetCommentFieldBuilder() {
      if (commentBuilder_ == null) {
        commentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.ondewo.nlu.Comment, com.ondewo.nlu.Comment.Builder, com.ondewo.nlu.CommentOrBuilder>(
                getComment(),
                getParentForChildren(),
                isClean());
        comment_ = null;
      }
      return commentBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.UpdateSessionCommentsRequest)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.UpdateSessionCommentsRequest)
  private static final com.ondewo.nlu.UpdateSessionCommentsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.UpdateSessionCommentsRequest();
  }

  public static com.ondewo.nlu.UpdateSessionCommentsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateSessionCommentsRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateSessionCommentsRequest>() {
    @java.lang.Override
    public UpdateSessionCommentsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateSessionCommentsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateSessionCommentsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.UpdateSessionCommentsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

