// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/entity_type.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

/**
 * <pre>
 * The request message for &lt;a href="index.html#ondewo.nlu.EntityTypes.UpdateEntityType"&gt;EntityTypes.UpdateEntityType&lt;/a&gt;.
 * </pre>
 *
 * Protobuf type {@code ondewo.nlu.UpdateEntityTypeRequest}
 */
@com.google.protobuf.Generated
public final class UpdateEntityTypeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ondewo.nlu.UpdateEntityTypeRequest)
    UpdateEntityTypeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      UpdateEntityTypeRequest.class.getName());
  }
  // Use UpdateEntityTypeRequest.newBuilder() to construct.
  private UpdateEntityTypeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateEntityTypeRequest() {
    languageCode_ = "";
    entityTypeView_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_UpdateEntityTypeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_UpdateEntityTypeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ondewo.nlu.UpdateEntityTypeRequest.class, com.ondewo.nlu.UpdateEntityTypeRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ENTITY_TYPE_FIELD_NUMBER = 1;
  private com.ondewo.nlu.EntityType entityType_;
  /**
   * <pre>
   * Required. The entity type to update.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
   * @return Whether the entityType field is set.
   */
  @java.lang.Override
  public boolean hasEntityType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Required. The entity type to update.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
   * @return The entityType.
   */
  @java.lang.Override
  public com.ondewo.nlu.EntityType getEntityType() {
    return entityType_ == null ? com.ondewo.nlu.EntityType.getDefaultInstance() : entityType_;
  }
  /**
   * <pre>
   * Required. The entity type to update.
   * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
   * </pre>
   *
   * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
   */
  @java.lang.Override
  public com.ondewo.nlu.EntityTypeOrBuilder getEntityTypeOrBuilder() {
    return entityType_ == null ? com.ondewo.nlu.EntityType.getDefaultInstance() : entityType_;
  }

  public static final int LANGUAGE_CODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object languageCode_ = "";
  /**
   * <pre>
   * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
   * specified, the agent&amp;apos;s default language is used.
   * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
   * languages&lt;/a&gt; are supported.
   * Note: languages must be enabled in the agent, before they can be used.
   * </pre>
   *
   * <code>string language_code = 2;</code>
   * @return The languageCode.
   */
  @java.lang.Override
  public java.lang.String getLanguageCode() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
   * specified, the agent&amp;apos;s default language is used.
   * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
   * languages&lt;/a&gt; are supported.
   * Note: languages must be enabled in the agent, before they can be used.
   * </pre>
   *
   * <code>string language_code = 2;</code>
   * @return The bytes for languageCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageCodeBytes() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_MASK_FIELD_NUMBER = 3;
  private com.google.protobuf.FieldMask updateMask_;
  /**
   * <pre>
   * Optional. The mask to control which fields get updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 3;</code>
   * @return Whether the updateMask field is set.
   */
  @java.lang.Override
  public boolean hasUpdateMask() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Optional. The mask to control which fields get updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 3;</code>
   * @return The updateMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getUpdateMask() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }
  /**
   * <pre>
   * Optional. The mask to control which fields get updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }

  public static final int ENTITY_TYPE_VIEW_FIELD_NUMBER = 6;
  private int entityTypeView_ = 0;
  /**
   * <pre>
   * Optional. The resource view to apply to the returned Entity Type
   * </pre>
   *
   * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
   * @return The enum numeric value on the wire for entityTypeView.
   */
  @java.lang.Override public int getEntityTypeViewValue() {
    return entityTypeView_;
  }
  /**
   * <pre>
   * Optional. The resource view to apply to the returned Entity Type
   * </pre>
   *
   * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
   * @return The entityTypeView.
   */
  @java.lang.Override public com.ondewo.nlu.EntityTypeView getEntityTypeView() {
    com.ondewo.nlu.EntityTypeView result = com.ondewo.nlu.EntityTypeView.forNumber(entityTypeView_);
    return result == null ? com.ondewo.nlu.EntityTypeView.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getEntityType());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(languageCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, languageCode_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getUpdateMask());
    }
    if (entityTypeView_ != com.ondewo.nlu.EntityTypeView.ENTITY_TYPE_VIEW_UNSPECIFIED.getNumber()) {
      output.writeEnum(6, entityTypeView_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEntityType());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(languageCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, languageCode_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUpdateMask());
    }
    if (entityTypeView_ != com.ondewo.nlu.EntityTypeView.ENTITY_TYPE_VIEW_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, entityTypeView_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ondewo.nlu.UpdateEntityTypeRequest)) {
      return super.equals(obj);
    }
    com.ondewo.nlu.UpdateEntityTypeRequest other = (com.ondewo.nlu.UpdateEntityTypeRequest) obj;

    if (hasEntityType() != other.hasEntityType()) return false;
    if (hasEntityType()) {
      if (!getEntityType()
          .equals(other.getEntityType())) return false;
    }
    if (!getLanguageCode()
        .equals(other.getLanguageCode())) return false;
    if (hasUpdateMask() != other.hasUpdateMask()) return false;
    if (hasUpdateMask()) {
      if (!getUpdateMask()
          .equals(other.getUpdateMask())) return false;
    }
    if (entityTypeView_ != other.entityTypeView_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEntityType()) {
      hash = (37 * hash) + ENTITY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEntityType().hashCode();
    }
    hash = (37 * hash) + LANGUAGE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageCode().hashCode();
    if (hasUpdateMask()) {
      hash = (37 * hash) + UPDATE_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateMask().hashCode();
    }
    hash = (37 * hash) + ENTITY_TYPE_VIEW_FIELD_NUMBER;
    hash = (53 * hash) + entityTypeView_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ondewo.nlu.UpdateEntityTypeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ondewo.nlu.UpdateEntityTypeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.ondewo.nlu.UpdateEntityTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ondewo.nlu.UpdateEntityTypeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message for &lt;a href="index.html#ondewo.nlu.EntityTypes.UpdateEntityType"&gt;EntityTypes.UpdateEntityType&lt;/a&gt;.
   * </pre>
   *
   * Protobuf type {@code ondewo.nlu.UpdateEntityTypeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ondewo.nlu.UpdateEntityTypeRequest)
      com.ondewo.nlu.UpdateEntityTypeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_UpdateEntityTypeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_UpdateEntityTypeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ondewo.nlu.UpdateEntityTypeRequest.class, com.ondewo.nlu.UpdateEntityTypeRequest.Builder.class);
    }

    // Construct using com.ondewo.nlu.UpdateEntityTypeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetEntityTypeFieldBuilder();
        internalGetUpdateMaskFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      entityType_ = null;
      if (entityTypeBuilder_ != null) {
        entityTypeBuilder_.dispose();
        entityTypeBuilder_ = null;
      }
      languageCode_ = "";
      updateMask_ = null;
      if (updateMaskBuilder_ != null) {
        updateMaskBuilder_.dispose();
        updateMaskBuilder_ = null;
      }
      entityTypeView_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ondewo.nlu.EntityTypeProto.internal_static_ondewo_nlu_UpdateEntityTypeRequest_descriptor;
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateEntityTypeRequest getDefaultInstanceForType() {
      return com.ondewo.nlu.UpdateEntityTypeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateEntityTypeRequest build() {
      com.ondewo.nlu.UpdateEntityTypeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ondewo.nlu.UpdateEntityTypeRequest buildPartial() {
      com.ondewo.nlu.UpdateEntityTypeRequest result = new com.ondewo.nlu.UpdateEntityTypeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ondewo.nlu.UpdateEntityTypeRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entityType_ = entityTypeBuilder_ == null
            ? entityType_
            : entityTypeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.languageCode_ = languageCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.updateMask_ = updateMaskBuilder_ == null
            ? updateMask_
            : updateMaskBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.entityTypeView_ = entityTypeView_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ondewo.nlu.UpdateEntityTypeRequest) {
        return mergeFrom((com.ondewo.nlu.UpdateEntityTypeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ondewo.nlu.UpdateEntityTypeRequest other) {
      if (other == com.ondewo.nlu.UpdateEntityTypeRequest.getDefaultInstance()) return this;
      if (other.hasEntityType()) {
        mergeEntityType(other.getEntityType());
      }
      if (!other.getLanguageCode().isEmpty()) {
        languageCode_ = other.languageCode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasUpdateMask()) {
        mergeUpdateMask(other.getUpdateMask());
      }
      if (other.entityTypeView_ != 0) {
        setEntityTypeViewValue(other.getEntityTypeViewValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetEntityTypeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              languageCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetUpdateMaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 48: {
              entityTypeView_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.ondewo.nlu.EntityType entityType_;
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.EntityType, com.ondewo.nlu.EntityType.Builder, com.ondewo.nlu.EntityTypeOrBuilder> entityTypeBuilder_;
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     * @return Whether the entityType field is set.
     */
    public boolean hasEntityType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     * @return The entityType.
     */
    public com.ondewo.nlu.EntityType getEntityType() {
      if (entityTypeBuilder_ == null) {
        return entityType_ == null ? com.ondewo.nlu.EntityType.getDefaultInstance() : entityType_;
      } else {
        return entityTypeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    public Builder setEntityType(com.ondewo.nlu.EntityType value) {
      if (entityTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entityType_ = value;
      } else {
        entityTypeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    public Builder setEntityType(
        com.ondewo.nlu.EntityType.Builder builderForValue) {
      if (entityTypeBuilder_ == null) {
        entityType_ = builderForValue.build();
      } else {
        entityTypeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    public Builder mergeEntityType(com.ondewo.nlu.EntityType value) {
      if (entityTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          entityType_ != null &&
          entityType_ != com.ondewo.nlu.EntityType.getDefaultInstance()) {
          getEntityTypeBuilder().mergeFrom(value);
        } else {
          entityType_ = value;
        }
      } else {
        entityTypeBuilder_.mergeFrom(value);
      }
      if (entityType_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    public Builder clearEntityType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      entityType_ = null;
      if (entityTypeBuilder_ != null) {
        entityTypeBuilder_.dispose();
        entityTypeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    public com.ondewo.nlu.EntityType.Builder getEntityTypeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetEntityTypeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    public com.ondewo.nlu.EntityTypeOrBuilder getEntityTypeOrBuilder() {
      if (entityTypeBuilder_ != null) {
        return entityTypeBuilder_.getMessageOrBuilder();
      } else {
        return entityType_ == null ?
            com.ondewo.nlu.EntityType.getDefaultInstance() : entityType_;
      }
    }
    /**
     * <pre>
     * Required. The entity type to update.
     * Format: &lt;pre&gt;&lt;code&gt;projects/&amp;lt;project_uuid&amp;gt;/agent/entityTypes/&amp;lt;entity_type_uuid&amp;gt;&lt;/code&gt;&lt;/pre&gt;
     * </pre>
     *
     * <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.ondewo.nlu.EntityType, com.ondewo.nlu.EntityType.Builder, com.ondewo.nlu.EntityTypeOrBuilder> 
        internalGetEntityTypeFieldBuilder() {
      if (entityTypeBuilder_ == null) {
        entityTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.ondewo.nlu.EntityType, com.ondewo.nlu.EntityType.Builder, com.ondewo.nlu.EntityTypeOrBuilder>(
                getEntityType(),
                getParentForChildren(),
                isClean());
        entityType_ = null;
      }
      return entityTypeBuilder_;
    }

    private java.lang.Object languageCode_ = "";
    /**
     * <pre>
     * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
     * specified, the agent&amp;apos;s default language is used.
     * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
     * languages&lt;/a&gt; are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     * </pre>
     *
     * <code>string language_code = 2;</code>
     * @return The languageCode.
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
     * specified, the agent&amp;apos;s default language is used.
     * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
     * languages&lt;/a&gt; are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     * </pre>
     *
     * <code>string language_code = 2;</code>
     * @return The bytes for languageCode.
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
     * specified, the agent&amp;apos;s default language is used.
     * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
     * languages&lt;/a&gt; are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     * </pre>
     *
     * <code>string language_code = 2;</code>
     * @param value The languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      languageCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
     * specified, the agent&amp;apos;s default language is used.
     * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
     * languages&lt;/a&gt; are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     * </pre>
     *
     * <code>string language_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguageCode() {
      languageCode_ = getDefaultInstance().getLanguageCode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The language of entity synonyms defined in &lt;code&gt;entity_type&lt;/code&gt;. If not
     * specified, the agent&amp;apos;s default language is used.
     * &lt;a href="https://dialogflow.com/docs/reference/language"&gt;More than a dozen
     * languages&lt;/a&gt; are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     * </pre>
     *
     * <code>string language_code = 2;</code>
     * @param value The bytes for languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      languageCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.FieldMask updateMask_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> updateMaskBuilder_;
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     * @return Whether the updateMask field is set.
     */
    public boolean hasUpdateMask() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     * @return The updateMask.
     */
    public com.google.protobuf.FieldMask getUpdateMask() {
      if (updateMaskBuilder_ == null) {
        return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
      } else {
        return updateMaskBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public Builder setUpdateMask(com.google.protobuf.FieldMask value) {
      if (updateMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateMask_ = value;
      } else {
        updateMaskBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public Builder setUpdateMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (updateMaskBuilder_ == null) {
        updateMask_ = builderForValue.build();
      } else {
        updateMaskBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public Builder mergeUpdateMask(com.google.protobuf.FieldMask value) {
      if (updateMaskBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          updateMask_ != null &&
          updateMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
          getUpdateMaskBuilder().mergeFrom(value);
        } else {
          updateMask_ = value;
        }
      } else {
        updateMaskBuilder_.mergeFrom(value);
      }
      if (updateMask_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public Builder clearUpdateMask() {
      bitField0_ = (bitField0_ & ~0x00000004);
      updateMask_ = null;
      if (updateMaskBuilder_ != null) {
        updateMaskBuilder_.dispose();
        updateMaskBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public com.google.protobuf.FieldMask.Builder getUpdateMaskBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetUpdateMaskFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
      if (updateMaskBuilder_ != null) {
        return updateMaskBuilder_.getMessageOrBuilder();
      } else {
        return updateMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
      }
    }
    /**
     * <pre>
     * Optional. The mask to control which fields get updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        internalGetUpdateMaskFieldBuilder() {
      if (updateMaskBuilder_ == null) {
        updateMaskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getUpdateMask(),
                getParentForChildren(),
                isClean());
        updateMask_ = null;
      }
      return updateMaskBuilder_;
    }

    private int entityTypeView_ = 0;
    /**
     * <pre>
     * Optional. The resource view to apply to the returned Entity Type
     * </pre>
     *
     * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @return The enum numeric value on the wire for entityTypeView.
     */
    @java.lang.Override public int getEntityTypeViewValue() {
      return entityTypeView_;
    }
    /**
     * <pre>
     * Optional. The resource view to apply to the returned Entity Type
     * </pre>
     *
     * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @param value The enum numeric value on the wire for entityTypeView to set.
     * @return This builder for chaining.
     */
    public Builder setEntityTypeViewValue(int value) {
      entityTypeView_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The resource view to apply to the returned Entity Type
     * </pre>
     *
     * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @return The entityTypeView.
     */
    @java.lang.Override
    public com.ondewo.nlu.EntityTypeView getEntityTypeView() {
      com.ondewo.nlu.EntityTypeView result = com.ondewo.nlu.EntityTypeView.forNumber(entityTypeView_);
      return result == null ? com.ondewo.nlu.EntityTypeView.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Optional. The resource view to apply to the returned Entity Type
     * </pre>
     *
     * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @param value The entityTypeView to set.
     * @return This builder for chaining.
     */
    public Builder setEntityTypeView(com.ondewo.nlu.EntityTypeView value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      entityTypeView_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The resource view to apply to the returned Entity Type
     * </pre>
     *
     * <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityTypeView() {
      bitField0_ = (bitField0_ & ~0x00000008);
      entityTypeView_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ondewo.nlu.UpdateEntityTypeRequest)
  }

  // @@protoc_insertion_point(class_scope:ondewo.nlu.UpdateEntityTypeRequest)
  private static final com.ondewo.nlu.UpdateEntityTypeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ondewo.nlu.UpdateEntityTypeRequest();
  }

  public static com.ondewo.nlu.UpdateEntityTypeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateEntityTypeRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateEntityTypeRequest>() {
    @java.lang.Override
    public UpdateEntityTypeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateEntityTypeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateEntityTypeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ondewo.nlu.UpdateEntityTypeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

