// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ondewo/nlu/common.proto
// Protobuf Java Version: 4.32.0

package com.ondewo.nlu;

@com.google.protobuf.Generated
public interface UpdateNotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ondewo.nlu.UpdateNotificationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The notification to update, identified by its resource name.
   * </pre>
   *
   * <code>.ondewo.nlu.Notification notification = 1;</code>
   * @return Whether the notification field is set.
   */
  boolean hasNotification();
  /**
   * <pre>
   * The notification to update, identified by its resource name.
   * </pre>
   *
   * <code>.ondewo.nlu.Notification notification = 1;</code>
   * @return The notification.
   */
  com.ondewo.nlu.Notification getNotification();
  /**
   * <pre>
   * The notification to update, identified by its resource name.
   * </pre>
   *
   * <code>.ondewo.nlu.Notification notification = 1;</code>
   */
  com.ondewo.nlu.NotificationOrBuilder getNotificationOrBuilder();

  /**
   * <pre>
   * Mask controlling which fields of the notification are updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * Mask controlling which fields of the notification are updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * Mask controlling which fields of the notification are updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();

  /**
   * <pre>
   * Optional. Mask to control which fields of the returned notification are filled with data.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return Whether the fieldMask field is set.
   */
  boolean hasFieldMask();
  /**
   * <pre>
   * Optional. Mask to control which fields of the returned notification are filled with data.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   * @return The fieldMask.
   */
  com.google.protobuf.FieldMask getFieldMask();
  /**
   * <pre>
   * Optional. Mask to control which fields of the returned notification are filled with data.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 3;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder();
}
